flanksource/flanksource-ui

src/components/Canary/table.js
=> feat: use namespace as secondary sorting (after check's displayed name)

src/components/Canary/FilterForm/index.jsx, src/components/Canary/index.js, src/components/Canary/tabs.js, src/components/Sidebar/index.js, src/components/StatCard/index.js
=> feat: collapsible filter sidebar

src/components/HealthSummary/summary.js, src/components/Topology/TopologyCard/TopologyCard.js, src/components/Topology/TopologyCardLarge/TopologyCardLarge.js, src/components/Topology/TopologyCardMedium/TopologyCardMedium.js, src/components/Topology/TopologyCardSmall/TopologyCardSmall.js, src/components/Topology/TopologyDropdownMenu/TopologyDropdownMenu.js, src/components/Topology/prop-types.js, src/data/topology.json, src/icons/index.js, src/pages/Examples/TopologyPageLarge/TopologyPageLargeView.js, src/pages/Examples/TopologyPageMedium/TopologyPageMediumView.js, src/pages/Examples/TopologyPageSmall/TopologyPageSmallView.js
1. hover effects for dropdown menu button
2. hover effects for dropdown menu items
3. card selection on card mouse click / enter, space press
=> fix: card selection on click and menu items / button effects

src/components/HypothesisBuilder/components/HypothesisDetailsTitle/index.js, src/components/HypothesisBuilder/hypothesis-details.js, src/components/HypothesisBuilder/hypothesis-title.js, src/components/HypothesisBuilder/index.js, src/components/Modal/index.js
=> fix: move hypothesis title to modal title

src/components/IncidentDetails/index.js, src/pages/incident/incident-details.js
https://github.com/flanksource/flanksource-ui/issues/169
=> Fix: updating priority in incident details

src/components/EditableText/index.js, src/components/HypothesisBuilder/hypothesis-title.js
https://github.com/flanksource/flanksource-ui/issues/170
=> feat: EditableText added check and x button

src/components/Dropdown/index.js, src/pages/Examples/dropdown-demo.js
Also added a demo example at `/examples/dropdown` page
=> fix: Dropdown component not working if using control

src/App.js, src/components/Layout/minimal.js, src/components/TopologyDropdown/index.js, src/pages/Examples/topology-dropdown.js
https://github.com/flanksource/flanksource-ui/issues/155
=> Feat: topology dropdown

src/App.js, src/index.js
Needs to be merged to main (with a version bump) for the React-minified error to be fixed in incident-commander production (https://incident-commander.canary.lab.flanksource.com/)
=> fix: move BrowserRouter into App to enable App to be imported/consumed

src/components/AccordionBox/index.js, src/components/Avatar/index.js, src/components/Badge/index.js, src/components/BannerMessage/index.js, src/components/Button/index.js, src/components/Canary/minimal.js, src/components/CanaryInterface/minimal.js, src/components/ConfigViewer/columns.js, src/pages/logs-page.js
=> component memoization changes

.eslintignore, public/_redirects, src/components/Logs/LogsViewer.stories.jsx, src/components/Logs/Table/logs-table.js, src/components/Logs/index.js, src/constants/index.js, src/pages/logs-page.js
- handled logs loading on query changes
- removed current behaviour of loading logs on page load.
=> handled logs loading on query changes

src/components/Canary/CanaryPopup/CheckDetails.js, src/components/Canary/Columns/columns.js, src/components/Canary/filter.js, src/components/Canary/grouping.js, src/components/Canary/index.js, src/components/Canary/state/index.js, src/components/Dropdown/GroupByDropdown.jsx
Closes https://github.com/flanksource/flanksource-ui/issues/278
=> fix: change health page default grouping to `canary_name`

src/components/ConfigList/ConfigList.stories.tsx, src/components/ConfigList/ConfigList.tsx, src/components/ConfigList/index.tsx, src/components/DataTable/DataTable.stories.jsx, src/components/DataTable/index.js, src/data/sampleConfigList.ts, src/pages/config/config-list.js
Closes: https://github.com/flanksource/flanksource-ui/issues/272 
Closes: https://github.com/flanksource/flanksource-ui/issues/210
=> feat: Show tags in Config List page

src/api/services/incident.js, src/components/HypothesisBuilder/evidence-section.js, src/components/HypothesisBuilder/hypothesis-bar.js, src/components/Incidents/IncidentCreate/index.js, src/components/Logs/Table/logs-table.js, src/pages/incident/incident-details.js
- On incident creation, redirect only after evidence has been created.
- Show icons on hypothesis bar, based on evidence and comments.
- Fix log page error
=> Few fixes in incident page

src/api/auth.js
=> Remove hardcoded user id for auth

src/components/Canary/index.js
=> fix: add loader in health page

src/components/Hypothesis/EvidenceSection/index.tsx
=> fix: removed add evidence button

src/components/Dropdown/SubtleDropdown.tsx, src/components/Hypothesis/HypothesisBar/index.tsx
=> collapse hypothesis only for click on title

.github/workflows/publish.yaml, .releaserc
=> remove semver options from publish action

src/api/services/evidence.ts, src/components/Hypothesis/EvidenceSection/index.tsx, src/components/Icon/index.js, src/components/IncidentDetails/index.tsx, src/pages/config/config-details.js
add config item in evidence item under incedents
**Note:** This won't work for the previously added evidences and will only work for the evidences added after the code is included.
=> feat: add config item in evidence item under incedents

src/pages/TopologyPage.tsx
=> feat: set flatten to true, when topology type is selected

src/pages/TopologyPage.tsx
=> fix: remove extra filter by team on topology page

src/components/ConfigList/index.tsx
This is what it looks like now:
Related to #531
=> fix: fix config changes column not wrapping items

src/App.tsx, src/components/Canary/index.tsx, src/components/Layout/SidebarLayout.tsx, src/components/SkeletonLoader/CardsSkeletonLoader.tsx, src/components/SkeletonLoader/FullPageSkeletonLoader.tsx, src/components/SkeletonLoader/HealthPageSkeletonLoader.tsx, src/pages/TopologyPage.tsx
=> fix: fix typo on skeleton components 

src/components/TopologyPopover/topologySort.tsx, src/utils/common.js
This reverts commit ca9efb879d1ae926a9489c324e3c28411970b542.
=> Revert "fix: persisting & restoring sort order & sort type values"

src/components/Canary/CanaryStatusChart/index.tsx
=> fix: reverse canary status chart time range

package-lock.json, package.json
Builds are failing as the version of netlify we are using isn't supported.
=> fix: update netlify next plugin, version not supported

src/api/services/configs.ts, src/components/ConfigRelated/index.tsx
=> feat: show reverse config relationships in the database

src/api/query-hooks/index.ts, src/api/services/configs.ts, src/components/BreadcrumbNav/index.jsx, src/components/ConfigBreadcrumb/index.tsx, src/components/Dropdown/ComponentNamesDropdown/index.tsx, src/components/Layout/ConfigLayout.tsx, src/pages/LogsPage.tsx, src/pages/config/ConfigDetailsPage.tsx, src/pages/config/ConfigList.tsx, src/pages/config/config-changes.jsx, src/pages/config/config-details-changes.jsx
=> chore: code refactor of config fetch api to use config views

src/components/TopologyCardIncidentSummary/index.tsx, src/context/TopologyPageContext.tsx
before incident severity came in as numeric - 1,2,3 and now it comes in as text - Low, Medium, High
=> fix: fix topology incident summary to api data shape

src/api/services/topology.ts, src/components/Badge/index.tsx, src/components/Canary/CanaryPopup/CheckTitle.tsx, src/components/Canary/CanarySearchBar/index.tsx, src/components/Canary/HealthCheckEdit/index.tsx, src/components/Canary/index.tsx, src/components/Canary/minimal.tsx, src/components/CanaryInterface/minimal.tsx, src/components/Dropdown/GroupByDropdown.tsx, src/components/Dropdown/TabByDropdown.tsx, src/components/Toggle/index.tsx, src/components/TristateToggle/index.tsx, src/context/HealthPageContext.tsx, src/pages/health.tsx, src/types/healthChecks.ts
This PR is built on top of #450
Closes #523
=> 523-canary-add-edit

src/components/AttachEvidenceDialog/index.tsx, src/components/TopologyCard/TopologyDropdownMenu.tsx, src/components/TopologyCard/index.tsx, src/pages/TopologyPage.tsx
=> 621-increase-guttercolumn-gap-on-topology-cards-with-2-columns

src/components/Canary/filter.ts, src/components/CanaryInterface/minimal.tsx, src/components/RefreshDropdown/index.tsx, src/components/SkeletonLoader/HealthPageSkeletonLoader.tsx
=> 634-health-page-unchecking-hide-passing-doesnt-work

src/api/query-hooks/index.ts, src/api/services/incident.ts, src/components/Hypothesis/HypothesisBuilder/index.tsx, src/components/IncidentDetails/DefinitionOfDone/EvidenceView/index.tsx, src/components/IncidentDetails/DefinitionOfDone/index.tsx, src/components/IncidentDetails/IncidentDetails.stories.tsx, src/components/IncidentDetails/ResponderDetailsDialog/index.tsx, src/components/IncidentDetails/index.tsx, src/pages/incident/IncidentDetails.tsx
=> 643-hypothesis-details-should-have-a-fixed-width

src/components/Canary/CanaryPopup/CanaryCheckDetailsLabel.tsx, src/components/Canary/CanaryPopup/CanaryCheckDetailsSpec.tsx, src/components/Canary/CanaryPopup/CheckDetails.tsx, src/components/Canary/CanaryPopup/CheckTitle.tsx, src/components/Canary/CanaryPopup/StatusHistory.tsx, src/components/Canary/minimal.tsx, src/components/ReactSelectDropdown/index.tsx
=> fix: fix health page refresh dropdown overlay stacking

src/api/services/incident.ts, src/components/CollapsiblePanel/index.tsx, src/components/IncidentsFilterBar/index.tsx, src/components/ReactSelectDropdown/index.tsx, src/components/Sidebars/incidents.tsx, src/components/Title/title.tsx, src/components/TopologyCard/CardMetrics.tsx, src/components/TopologyConfigChanges/index.tsx, src/components/TopologySidebar/index.tsx
Minor UI Changes:
- Topology Incidents,  Filters Controls Behavior was weird
- Fix UI Color contrast for the TopologyCard  - Closes #624
- Fix the empty state missing on the topology config changes- when no items were available, it showed empty space only
=> Fix-topology-details-sidebar-issues

src/components/Hypothesis/CreateHypothesis/index.tsx, src/components/Incidents/IncidentCreate/index.tsx, src/components/ReactSelectDropdown/index.tsx
=> fix: fix incident create form labels being inconsistent

src/components/FilterLogs/FilterLogsByComponent.tsx
=> 656-component-dropdown-should-show-none-instead-of-all

src/components/ConfigSidebar/ConfigDetails.tsx, src/components/ConfigSidebar/index.tsx, src/components/ConfigsPage/ConfigLayout.tsx, src/components/DescriptionCard/index.tsx, src/components/TopologyCard/Property.tsx, src/components/TopologyDetails/index.tsx, src/constants/index.ts, src/pages/config/ConfigDetailsPage.tsx
=> 657-config-details-switch-tags-to-sidebar-like-the-topology-details

src/components/SkeletonLoader/CardsSkeletonLoader.tsx, src/components/SkeletonLoader/IncidentDetailsPageSkeletonLoader.tsx, src/pages/incident/IncidentDetails.tsx
=> 697: Incident Details Page - Switch to skeleton loader

src/api/axios.js, src/api/query-hooks/index.ts, src/api/services/configs.ts, src/components/AttachEvidenceDialog/index.tsx, src/components/ConfigAnalysisLink/ConfigAnalysisLink.tsx, src/components/ConfigChanges/index.tsx, src/components/ConfigDetailsChanges/ConfigDetailsChanges.tsx, src/components/ConfigInsights/index.tsx, src/components/ConfigLink/ConfigLink.tsx, src/components/Description/description.js, src/components/DescriptionCard/index.tsx, src/components/Hypothesis/EvidenceSection/index.tsx, src/components/Icon/index.tsx, src/components/IncidentDetails/DefinitionOfDone/EvidenceSelectionModal.tsx, src/components/IncidentDetails/DefinitionOfDone/EvidenceView/index.tsx, src/components/IncidentDetails/DefinitionOfDone/index.tsx, src/components/Modal/index.tsx, src/types/index.ts
=> feat: add support for linking config analysis as evidence to incident

src/api/services/teams.ts, src/components/EmptyState/index.tsx, src/components/SchemaResourcePage/SchemaResourceEdit.tsx, src/components/SchemaResourcePage/resourceTypes.tsx, src/components/TeamMembers/TeamMembers.tsx
=> feat: team members management support

src/components/Canary/index.tsx, src/components/Canary/minimal.tsx, src/components/TopologyPopover/index.tsx, src/components/TopologyPopover/topologyPreference.tsx, src/components/TopologyPopover/topologySort.tsx, src/pages/TopologyPage.tsx
=> 676-sorting-time-ranges-should-not-be-pushed-to-history

src/components/Canary/index.tsx, src/components/Canary/labels.js, src/components/CanaryInterface/minimal.tsx, src/components/TristateToggle/index.tsx
=> fix: health page filter fixes

next.config.js
=> chore: update next js re-writes to accommodate snapshot

next.config.js
Reverts flanksource/flanksource-ui#723
=> Revert "chore: update next js re-writes to accommodate snapshot"

src/components/Canary/index.tsx
=> chore: label filters arrangement is sorted by label

src/components/DataTable/index.tsx
=> fix: fix config list loading animation out of alignment

src/pages/LogsPage.tsx
=> 727 Logs page loading icon spinning when no component Is selected

next.config.js
=> Update NextJS Config Files Re-Write Rules for Wildcard

src/components/IncidentDetails/DefinitionOfDone/index.tsx
=> fix: do not reloading icons when refetching dod

src/components/IconButton/index.tsx, src/components/Sidebars/configs.tsx
=> feat:  add deleted items filter resolution to configs section on Configs details page

src/components/SchemaResourcePage/index.tsx, src/components/TopologyBreadcrumbs/index.tsx, src/pages/LogsPage.tsx, src/pages/TopologyPage.tsx, src/pages/UsersPage.tsx, src/pages/config/ConfigDetailsChangesPage.tsx, src/pages/config/ConfigDetailsPage.tsx, src/pages/config/ConfigList.tsx, src/pages/config/configChanges.tsx, src/pages/health.tsx, src/pages/incident/IncidentDetails.tsx, src/pages/incident/IncidentListPage.tsx
=> 622 set page title for different pages in the app

src/components/Changelog/IncidentChangelog.tsx, src/components/CollapsiblePanel/index.tsx, src/components/ConfigChanges/index.tsx, src/components/ConfigInsights/index.tsx, src/components/Sidebars/incidents.tsx, src/components/TopologyConfigChanges/index.tsx, src/components/VerticalScrollView/VerticalScrollView.tsx
=> fix: add vertical scroll for sidebar sections content

src/api/query-hooks/mutations/useUpdateEvidenceMutation.tsx, src/api/services/configs.ts, src/api/services/evidence.ts, src/components/CodeEditor/index.tsx, src/components/IncidentDetails/AddDefinitionOfDone/AddDefinitionOfDoneStepper.tsx, src/components/IncidentDetails/AddDefinitionOfDone/steps/EvidenceSelectorStep.tsx, src/components/IncidentDetails/AddDefinitionOfDone/steps/ScriptStep.tsx, src/components/IncidentDetails/DefinitionOfDone/EditEvidenceDefinitionOfDoneScript.tsx, src/components/IncidentDetails/DefinitionOfDone/IncidentsDefinitionOfDone.tsx, src/components/IncidentDetails/DefinitionOfDone/IncidentsDefinitionOfDoneItem.tsx, src/components/IncidentDetails/DefinitionOfDone/index.tsx, src/components/IncidentDetails/index.tsx, src/components/Modal/index.tsx, src/components/SchemaResourcePage/SchemaResourceEdit.tsx
=> 552-definition-of-done-add-script

src/api/axios.js, src/api/services/topology.ts, src/components/ReactSelectDropdown/index.tsx, src/components/TopologyCard/TopologyDropdownMenu.tsx, src/components/TopologyCard/TopologySnapshotModal.tsx, src/components/TopologyCard/useDownloadTopologySnapshot.tsx, src/context/TopologyPageContext.tsx
NB: It's timing out on related components because of Lambdas 3 sec timeout.
Closes #711
=> 711-topology-add-snapshot-action

src/api/services/IncidentsHistory.ts, src/components/Changelog/EvidenceChangelogContent.tsx, src/components/Changelog/IncidentChangelog.tsx, src/components/Changelog/IncidentHistoryItemTypeContent.tsx
=> feat: show evidence item instead of description in changelog

src/App.tsx, src/components/Layout/SidebarLayout.tsx
=> 751-Fix: expand settings sub menus when link is loaded or refreshed

src/App.tsx, src/api/query-hooks/index.ts, src/api/query-hooks/useJobsHistoryQuery.tsx, src/api/schemaResources.ts, src/api/services/IncidentsHistory.ts, src/api/services/jobsHistory.ts, src/components/Canary/tabs.tsx, src/components/ConfigsPage/ConfigsPageTabs.tsx, src/components/DataTable/index.tsx, src/components/JobsHistory/JobsHistoryDetails.tsx, src/components/JobsHistory/JobsHistorySettingsPage.tsx, src/components/JobsHistory/JobsHistoryTable.tsx, src/components/JobsHistory/JobsHistoryTableColumn.tsx, src/components/SchemaResourcePage/SchemaResource.tsx, src/components/SchemaResourcePage/SchemaResourceEdit.tsx, src/components/SchemaResourcePage/SchemaResourceEditJobsTab.tsx, src/components/SchemaResourcePage/index.tsx, src/components/SchemaResourcePage/resourceTypes.tsx, src/pages/config/configChanges.tsx
=> 649-add-topologycanaryscraper-history-tabs

src/components/Hypothesis/EvidenceSection/index.tsx, src/components/IncidentDetails/AddDefinitionOfDone/AddDefinitionOfDoneStepper.tsx, src/components/IncidentDetails/DefinitionOfDone/EvidenceView/index.tsx
=> fix: config evidence item icon issue

src/components/ConfigsListFilters/index.tsx, src/components/ReactSelectDropdown/index.tsx, src/components/TextInputClearable/index.tsx
=> 785-config-page-filter-controls-fields-are-small-and-not-expanding-to-fit-container-width

package-lock.json, src/components/BreadcrumbNav/ConfigsDetailsBreadCrumb.tsx, src/components/Canary/HealthCheckEdit/index.tsx, src/components/ConfigChanges/index.tsx, src/components/ConfigComponents/index.tsx, src/components/ConfigInsights/index.tsx, src/components/ConfigSidebar/ConfigDetails.tsx, src/components/DataTable/index.tsx, src/components/IncidentDetails/DefinitionOfDone/EvidenceView/index.tsx, src/components/Logs/Table/LogsTable.tsx, src/components/SchemaResourcePage/index.tsx, src/components/Sidebars/configs.tsx, src/components/SkeletonLoader/IncidentListSkeletonLoader.tsx, src/components/SkeletonLoader/TableSkeletonLoader.tsx, src/components/SkeletonLoader/TextSkeletonLoader.tsx, src/components/SkeletonLoader/TopologyCardSkeletonLoader.tsx, src/components/TopologyCard/index.tsx, src/components/TopologyConfigChanges/index.tsx, src/components/TopologySidebar/ComponentTeams.tsx, src/pages/UsersPage.tsx, src/pages/incident/IncidentListPage.tsx
=> feat: add skeleton loader for all components & pages

src/api/query-hooks/index.ts, src/api/services/configs.ts, src/components/ConfigCosts/index.tsx, src/components/ConfigInsights/index.tsx, src/components/ConfigList/Cells/ConfigListCostCell.tsx, src/components/ConfigList/ConfigListColumn.tsx, src/components/CostDetails/CostDetails.tsx, src/components/TopologySidebar/TopologyCost.tsx, src/components/TopologySidebar/TopologySidebar.tsx, src/context/TopologyPageContext.tsx
=> feat: extract cost info panel & integrate into config details side bar section

src/components/Chip/chip.tsx, src/components/HealthChecksSummary/index.tsx, src/components/HealthSummary/summary.tsx, src/components/IncidentCard/IncidentCard.tsx, src/components/IncidentCardSummary/index.tsx, src/components/IncidentStatusTag/index.tsx, src/components/Incidents/IncidentList/index.tsx, src/components/Sidebars/incidents.tsx, src/components/StatusLine/StatusLine.tsx, src/components/Tag/Tag.tsx, src/components/TopologyCard/index.tsx
=> fix: incident card styling fixes

src/components/SchemaResourcePage/SchemaResource.tsx
=> 788-Settings breadcrumb link is incorrect - duplicate path

src/api/services/incident.ts, src/components/IncidentCardSummary/index.tsx, src/pages/incident/IncidentListPage.tsx
=> fix: clicking on incident type opens incident listing page with type preselected

src/components/ConfigList/Cells/ConfigListTagsCell.tsx, src/components/Logs/Table/LogsTableCells.tsx, src/components/TagList/TagList.tsx
=> refactor: extract tag list component and integrated into config list & logs list component

src/components/TagList/TagList.tsx
=> fix: fixed tag list expand hiding tags issue

src/pages/TopologyPage.tsx
=> fix: topology refresh button animation

pages/global.css, src/api/query-hooks/mutations/useUpdateComponentMutation.tsx, src/api/services/topology.ts, src/components/Button/index.tsx, src/components/Modal/index.tsx, src/components/TopologyCard/TopologyDropdownMenu.tsx, src/components/TopologyCard/TopologySnapshotModal.tsx, src/components/TopologySidebar/TopologyActionBar.tsx, src/components/TopologySidebar/TopologySidebar.tsx, src/pages/TopologyPage.tsx
=> 781-add-action-bar-in-topology-sidebar

src/components/Changelog/IncidentChangelog.tsx, src/components/ClickableSvg/ClickableSvg.tsx, src/components/CollapsiblePanel/index.tsx, src/components/ConfigListToggledDeletedItems/ConfigListToggledDeletedItems.tsx, src/components/IncidentDetails/DefinitionOfDone/IncidentsDefinitionOfDone.tsx, src/components/IncidentDetails/IncidentSidebar.tsx, src/components/Popover/Popover.tsx, src/components/QueryBuilder/index.js, src/components/RefreshButton/index.tsx, src/components/Sidebar/index.js, src/components/TopologyPopover/topologyPreference.tsx, src/components/UserProfile/UserProfile.tsx
=> fix: add hover & active status styling to svg action buttons

src/api/query-hooks/mutations/evidence.tsx, src/api/query-hooks/mutations/hypothesis.tsx, src/api/services/evidence.ts, src/api/services/hypothesis.ts, src/components/Comment/CommentInput.tsx, src/components/Dialogs/ConfirmationPromptDialog.tsx, src/components/Hypothesis/Comments/index.tsx, src/components/Hypothesis/HypothesisCommentsViewContainer/HypothesisCommentsViewContainer.tsx, src/components/IncidentDetails/AddDefinitionOfDone/AddAutoDefinitionOfDone.tsx, src/components/IncidentDetails/AddDefinitionOfDone/AddDefinitionOfDoneHome.tsx, src/components/IncidentDetails/AddDefinitionOfDone/AddManualDefinitionOfDone.tsx, src/components/IncidentDetails/AddDefinitionOfDone/steps/EvidenceSelectorStep.tsx, src/components/IncidentDetails/AddDefinitionOfDone/useAddCommentAsDoD.tsx, src/components/IncidentDetails/DefinitionOfDone/EditEvidenceDefinitionOfDoneComment.tsx, src/components/IncidentDetails/DefinitionOfDone/EvidenceView/index.tsx, src/components/IncidentDetails/DefinitionOfDone/IncidentsDefinitionOfDone.tsx, src/components/IncidentDetails/DefinitionOfDone/IncidentsDefinitionOfDoneItem.tsx, src/components/IncidentDetails/IncidentSidebar.tsx
=> feat: allow add comments as definition of done

src/pages/config/ConfigDetailsChangesPage.tsx, src/pages/config/ConfigDetailsPage.tsx
=> fix: add vertical scroll to config-viewer & config changes table

package-lock.json, package.json, src/components/CodeEditor/index.tsx
=> feat: add monaco theme for both JSON and YAML

src/components/ConfigChangeHistory/index.tsx, src/components/ConfigDetailsChanges/ConfigDetailsChanges.tsx, src/pages/config/ConfigDetailsPage.tsx
=> Config Viewer: default preview code to yaml format

src/components/ConfigList/index.tsx
=> fix: config list sorting by name column issue fixed

src/api/query-hooks/index.ts, src/api/services/configs.ts, src/components/ConfigTagsDropdown/index.tsx, src/components/ReactSelectDropdown/index.tsx
=> feat: switch tag list source to config_tags view not configs

src/api/services/topology.ts, src/components/Canary/CanaryPopup/CheckDetails.tsx, src/components/Canary/CanaryPopup/StatusHistory.tsx, src/components/Canary/CanaryStatusChart/index.tsx, src/components/Canary/index.tsx, src/components/Canary/minimal.tsx, src/components/DataTable/index.tsx, src/constants/index.ts, src/utils/common.ts
=> fix: close health check modal on clicking esc button

src/components/Modal/index.tsx
=> fix: increase contrast for the modal close button and bg

src/App.tsx, src/api/query-hooks/useConfigAnalysisQuery.tsx, src/api/services/configs.ts, src/components/ConfigAnalysis/ConfigAnalysisSeverityDropdown.tsx, src/components/ConfigAnalysis/ConfigAnalysisTypeDropdown.tsx, src/components/ConfigAnalysis/ConfigInsightsColumns.tsx, src/components/ConfigAnalysis/ConfigInsightsFilters.tsx, src/components/ConfigAnalysis/ConfigInsightsList.tsx, src/components/ConfigAnalysisLink/ConfigAnalysisLink.tsx, src/components/ConfigAnalysisLink/ConfigInsightsDetailsModal.tsx, src/components/ConfigInsights/index.tsx, src/components/ConfigList/Cells/ConfigListAnalysisCell.tsx, src/components/ConfigsPage/ConfigsPageTabs.tsx, src/components/DataTable/Pagination/Pagination.tsx, src/components/DataTable/index.tsx, src/pages/config/ConfigInsightsList.tsx
=> feat: add config analysis tab for configs

src/components/ConfigTypesDropdown/index.tsx
Closes #847
---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.
=> fix: sort config type options

src/api/query-hooks/useComponentConfigChanges.tsx, src/api/query-hooks/useConfigComponentsRelationshipQuery.tsx, src/api/services/configs.ts, src/components/Changelog/IncidentChangelog.tsx, src/components/Chip/chip.tsx, src/components/ConfigChanges/index.tsx, src/components/ConfigComponents/index.tsx, src/components/ConfigInsights/index.tsx, src/components/ConfigSidebar/ConfigDetails.tsx, src/components/DetailsTable/DetailsTable.tsx, src/components/IncidentCard/IncidentCard.tsx, src/components/IncidentDetails/DefinitionOfDone/IncidentsDefinitionOfDone.tsx, src/components/IncidentDetails/IncidentSidebar.tsx, src/components/Sidebars/incidents.tsx, src/components/TopologyConfigChanges/index.tsx, src/components/TopologySidebar/ComponentTeams.tsx
=> 845 add count badge for detail panels

src/components/ConfigAnalysisLink/ConfigInsightsDetailsModal.tsx
=> 921 Add / between config and analysis in title for config popup

pages/_app.tsx, src/App.tsx, src/api/auth.ts, src/api/services/users.ts, src/components/EmptyState/index.tsx, src/components/Errors/ErrorPage.tsx, src/pages/config/ConfigDetailsPage.tsx, src/pages/incident/IncidentDetails.tsx
=> 629-handle-http-server-errors-5xx-more-elegantly-especially-on-the-peoples-endpoint

src/components/ConfigAnalysis/ConfigInsightsColumns.tsx, src/components/ConfigChangeHistory/ConfigChangeHistory.stories.jsx, src/components/ConfigChangeHistory/index.tsx, src/components/ConfigDetailsChanges/ConfigDetailsChanges.tsx
=> feat: config changes table columns list updated with source, summary and config & code refactor

src/App.tsx, src/__tests__/Canary/Colunms/columns.test.js, src/components/Canary/CanaryPopup/CheckDetails.tsx, src/components/Canary/CanaryPopup/CheckTitle.tsx, src/components/Canary/CanaryPopup/StatusHistory.tsx, src/components/Canary/Columns/columns.js, src/components/Canary/Columns/index.js, src/components/Canary/aggregate.js, src/components/Canary/filter.ts, src/components/Canary/index.tsx, src/components/Canary/minimal.tsx, src/components/Canary/table.tsx, src/components/SkeletonLoader/TopologyCardSkeletonLoader.tsx, src/components/Status/index.js, src/types/healthChecks.ts, src/utils/date.ts
=> feat: integrate check summary api & code refactor

src/components/ConfigList/ConfigListColumn.tsx
=> feat: config list add support for showing config analysis summary view in group by mode

src/components/ConfigList/Cells/ConfigListAnalysisCell.tsx, src/components/ConfigList/Cells/ConfigListTagsCell.tsx, src/components/Popover/Popover.tsx
=> fix: config tags & config analysis popover ui/ux improvements

src/components/Tabs/TabbedLinks.tsx, src/hooks/useRunTaskOnPropChange.ts, src/pages/config/ConfigDetailsChangesPage.tsx, src/pages/config/ConfigDetailsPage.tsx
=> fix: fixed config details page json viewer height issue

src/api/services/configs.ts, src/components/Canary/Columns/columns.js, src/components/ConfigChangeHistory/index.tsx, src/components/ConfigChanges/index.tsx, src/components/ConfigListToggledDeletedItems/ConfigListToggledDeletedItems.tsx
Closes #968
Closes #957
Closes #947
=> Fix a bunch of minor issues

src/components/TopologyPopover/topologySort.tsx
closes #848
---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.
=> fix: enable topology health sorting to work correctly

src/components/JobsHistory/JobsHistorySettingsPage.tsx, src/components/JobsHistory/JobsHistoryTable.tsx, src/components/JobsHistory/JobsHistoryTableColumn.tsx, src/components/SchemaResourcePage/SchemaResourceEditJobsTab.tsx
=> fix: fix topology item job item being empty when not

package-lock.json, package.json
This is to prevent netlify builds from failing
=> chore: upgrade @netlify/plugin-nextjs npm package

src/components/ConfigAnalysis/ConfigAnalysisTypeDropdown.tsx, src/components/ConfigInsightsIcon/index.tsx, src/components/ConfigList/Cells/ConfigListAnalysisCell.tsx, src/components/Incidents/data.tsx
=> 920 Add reliability analysis type to filters and data table icon/modal

src/components/SchemaResourcePage/SchemaResourceList.tsx
=> fix: resouces list table column mapping issue fixed

src/components/CustomScroll/index.tsx, src/components/TopologyCard/index.tsx
=> fix: remove component id from the topology card

src/api/schemaResources.ts, src/components/SchemaResourcePage/SchemaResource.tsx
=> feat: use name as breadcrumb and add page title

src/components/InviteUserForm/index.tsx, src/pages/UsersPage.tsx
Closes [#971](https://github.com/flanksource/flanksource-ui/issues/971)
https://www.awesomescreenshot.com/video/15896311?key=5a80609ba36f8bedcb76e642b655fe2f
---
=> fix: set invite user modal cancel button to also close the modal

src/api/schemaResources.ts, src/components/SchemaResourcePage/SchemaResourceList.stories.tsx, src/components/SchemaResourcePage/SchemaResourceList.tsx
=> feat: add job history status and last run at to component

src/components/ory/errors.tsx
closes #1008
[Loom video](https://www.loom.com/share/2d655b73aeb54139a828ba6f96975bc6)
---
=> fix: redirect the user to the login page on unauthorized access to profile-settings

src/components/Canary/index.tsx
=> fix: default hide passing filter to false

src/App.tsx, src/api/query-hooks/index.ts, src/components/BreadcrumbNav/ConfigsDetailsBreadCrumb.tsx, src/components/BreadcrumbNav/index.tsx, src/components/JobsHistory/JobsHistorySettingsPage.tsx, src/components/SchemaResourcePage/SchemaResourceList.tsx, src/components/SchemaResourcePage/index.tsx, src/components/TopologyBreadcrumbs/index.tsx, src/components/TopologyLink/index.tsx, src/pages/LogsPage.tsx, src/pages/TopologyPage.tsx, src/pages/UsersPage.tsx, src/pages/config/ConfigInsightsList.tsx, src/pages/config/ConfigList.tsx, src/pages/config/configChanges.tsx, src/pages/health.tsx, src/pages/incident/IncidentDetails.tsx, src/pages/incident/IncidentListPage.tsx
=> fix: sidebar menu arrangement changes & breadcrumbs code refactor

src/components/Canary/index.tsx, src/components/Dropdown/StandaloneWrapper.tsx, src/constants/index.ts
Closes #1048
[Demo](https://www.loom.com/share/4d45e92d5e904e44b7a34f58f9bc1a7d)
---
=> feat: Health - save settings to local storage

src/api/mutations/useCreateHypothesisMutation.js, src/components/Hypothesis/HypothesisBar/index.tsx, src/components/Hypothesis/HypothesisNode/index.tsx, src/pages/incident/IncidentDetails.tsx, src/store/hypothesis.state.ts
=> fix: expand factor on create

src/components/ConfigChangeHistory/index.tsx, src/components/ConfigDetailsChanges/ConfigDetailsChanges.tsx
=> feat: extracted config change details modal and reused changes list & changes panel

src/components/CollapsiblePanel/index.tsx, src/components/IncidentDetails/DefinitionOfDone/IncidentsDefinitionOfDone.tsx, src/components/IncidentDetails/DefinitionOfDone/IncidentsDefinitionOfDoneItem.tsx, src/components/Menu/index.tsx, src/components/SlidingSideBar/index.tsx, src/components/TopologyCard/TopologyDropdownMenu.tsx, src/components/TopologyCard/index.tsx, src/pages/TopologyPage.tsx
Prevent overflow showing when there isn't enough height
Closes #972 and Closes #942
=> 972-topology-card-context-menu-position-fixed-wont-hidden-less-height-accommodate

src/components/Canary/CanaryPopup/CanaryCheckDetailsUptime.tsx, src/components/Canary/CanaryPopup/CheckDetails.tsx, src/components/Canary/CanaryPopup/StatusHistory.tsx, src/components/Canary/minimal.tsx, src/components/Hypothesis/EvidenceSection/index.tsx
=> fix: removed redundant fields in check details tab

src/api/services/incident.ts, src/components/FilterIncidents/FilterIncidents.tsx, src/components/FilterIncidents/FilterIncidentsByComponents.tsx, src/components/FilterIncidents/FilterIncidentsByOwner.tsx, src/pages/incident/IncidentListPage.tsx
Closes #1046
[Demo](https://www.loom.com/share/d63a80220c82446bb257a226ef83c48e)
---
=> feat: Incident list - add search bar

src/components/ActionLink/ActionLink.tsx, src/components/ConfigSidebar/ConfigActionBar.tsx, src/components/ConfigSidebar/index.tsx, src/components/TopologySidebar/TopologyActionBar.tsx, src/pages/config/ConfigDetailsPage.tsx
=> fix: add attach to incident action button in config details page

src/components/Canary/minimal.tsx
Closes [#1066](https://github.com/flanksource/flanksource-ui/issues/1066)
[Loom Video](https://www.loom.com/share/1ae6519eec8649ccb2194f7dc10d60b9)
---
=> refactor: close analysis / health modal after attaching as evidence

src/api/services/teams.ts, src/components/TeamMembers/TeamMembers.tsx
closes #979
**Demo:**
[Loom video](https://www.loom.com/share/9e447f46177849869bdb99efc1abab6b)
---
=> fix: Added Team Members Don't Show Up in Teams Members Tab

src/api/query-hooks/index.ts, src/api/services/configs.ts, src/components/ChangesTypesDropdown/ChangeTypesDropdown.tsx, src/components/ConfigChangeSeverity/ConfigChangeSeverity.tsx, src/components/ConfigChangesFilters/ConfigChangesFilters.tsx, src/components/ConfigTypesDropdown/index.tsx, src/pages/config/ConfigChangesPage.tsx, src/pages/index.ts
Closes #924
* adds filters on config type, change type & severity for the config changes table
=> feat: add config changes filters

src/components/GroupByDropdown/index.tsx, src/components/IncidentDetails/IncidentSidebar.tsx, src/components/SchemaResourcePage/SchemaResourceEditJobsTab.tsx, src/components/Select/Select.stories.jsx, src/components/SpecEditor/SpecEditor.stories.tsx, src/components/TopologyCard/TopologyDropdownMenu.tsx, src/components/TopologySidebar/TopologySidebar.tsx
I have fixed job history not showing and fixed job status on the backend.
Closes #1059
=> 1059-configtopology-job-history-tab-not-filtered-correctly

src/components/Connections/ConnectionForm.tsx, src/components/FeatureFlags/FeatureFlagForm.tsx, src/components/SchemaResourcePage/SchemaResourceEdit.tsx, src/pages/ConnectionsPage.tsx, src/pages/FeatureFlagsPage.tsx
=> fix: remove edit button from settings resources froms

src/App.tsx, src/api/query-hooks/mutations/useSettingsResourcesMutations.tsx, src/api/schemaResources.ts, src/components/ConfigLink/ConfigLink.tsx, src/components/Forms/SpecEditorForm.stories.tsx, src/components/Forms/SpecEditorForm.tsx, src/components/Layout/SidebarLayout.tsx, src/components/Modal/index.tsx, src/components/SchemaResourcePage/Delete/DeleteResource.tsx, src/components/SchemaResourcePage/SchemaResource.stories.tsx, src/components/SchemaResourcePage/SchemaResource.tsx, src/components/SchemaResourcePage/SchemaResourceEdit.stories.tsx, src/components/SchemaResourcePage/SchemaResourceEdit.tsx, src/components/SchemaResourcePage/SchemaResourceList.stories.tsx, src/components/SchemaResourcePage/index.tsx, src/components/SchemaResourcePage/resourceTypes.tsx, src/components/SpecEditor/ConfigScrapperSpecEditor.tsx, src/components/SpecEditor/HealthSpecEditor.tsx, src/components/SpecEditor/SpecEditor.tsx, src/services/permissions/permissionsService.ts
Still remaining deletion implementation
Closes #1013 and Closes #1005
=> feat: confirm resources being deleted before deletion

src/components/CodeEditor/index.tsx, src/components/Forms/Formik/FormikTemplateFields.tsx, src/components/Forms/SpecEditorForm.tsx, src/components/SchemaResourcePage/SchemaResourceEdit.tsx, src/components/SchemaResourcePage/index.tsx, src/components/SpecEditor/SpecEditor.tsx, src/components/Switch/index.tsx, src/components/Tabs/Tabs.tsx
=> 1115-schema-forms-scroll

src/api/axios.ts, src/components/QueryBuilder/index.tsx, src/components/TextInputClearable/index.tsx
=> 964-config-list-advanced-mode-not-working

src/components/Forms/Configs/AWSConfigsFormEditor.tsx, src/components/Forms/Configs/KubernetesConfigsFormEditor.tsx, src/components/Forms/Formik/FormikScheduleField.tsx, src/components/Forms/Health/HTTPHealthFormEditor.tsx
=> fix: missing schedule for the config scrapper form

src/components/SchemaResourcePage/SchemaResourceEdit.tsx, src/components/TextInput/index.tsx
=> 1131-job-history-tab-missing

src/components/ConfigList/Cells/ConfigListTypeCell.tsx, src/components/Icon/index.tsx
=> fix: split type to get primary and secondary icons

package-lock.json, package.json, src/App.tsx, src/api/query-hooks/mutations/useSettingsResourcesMutations.tsx, src/api/schemaResources.ts, src/components/Connections/ConnectionsList.tsx, src/components/Forms/Formik/FormikCodeEditor.tsx, src/components/Forms/SpecEditorForm.tsx, src/components/LogBackends/LogBackends.ts, src/components/LogBackends/LogBackendsForm.tsx, src/components/LogBackends/LogBackendsList.tsx, src/components/SchemaResourcePage/Delete/DeleteResource.tsx, src/components/SchemaResourcePage/resourceTypes.tsx, src/pages/LogBackendsPage.tsx, src/services/permissions/resources.ts
=> 1122-settings-log-backends

src/App.tsx, src/api/auth.ts, src/api/query-hooks/settingsResourcesHooks.tsx, src/components/Errors/DashboardErrorBoundary.tsx, src/components/Errors/ErrorPage.tsx, src/components/Layout/search.tsx, src/components/SchemaResourcePage/SchemaResource.tsx, src/components/SchemaResourcePage/SchemaResourceEditJobsTab.tsx, src/components/SchemaResourcePage/index.tsx
=> 629-handle-http-server-errors-5xx-elegantly-especially-peoples-endpoint

src/api/query-hooks/useComponentConfigRelationshipQuery.ts, src/api/services/configs.ts
=> fix: fixed related configs fetch api service response converter

src/components/ConfigChanges/index.tsx, src/components/InfiniteTable/InfiniteTable.tsx, src/utils/date.ts
=> fix: change panel ui formatting fixes

src/components/FilterIncidents/FilterIncidentsByComponents.tsx, src/components/FilterLogs/FilterLogsByComponent.tsx
=> 1154-component-dropdown-list-narrow

src/api/services/configs.ts, src/api/services/topology.ts, src/components/Agents/AgentName.tsx, src/components/Canary/CanaryPopup/CheckDetails.tsx, src/components/Canary/CanaryPopup/CheckTitle.tsx, src/components/Canary/CanaryTabs.tsx, src/components/Canary/index.tsx, src/components/Canary/url.tsx, src/components/ConfigList/ConfigListColumn.tsx, src/components/Dropdown/GroupByDropdown.tsx, src/components/Dropdown/StandaloneWrapper.tsx, src/components/Dropdown/TabByDropdown.tsx, src/components/Dropdown/index.tsx, src/components/TopologyCard/TopologyCardAgent.tsx, src/components/TopologyCard/index.tsx, src/context/TopologyPageContext.tsx, src/pages/health.tsx, src/types/healthChecks.ts
=> 1137-show-agent-name

src/components/Canary/CanaryPopup/CheckDetails.tsx, src/components/Canary/CanaryPopup/StatusHistory/StatusHistory.tsx, src/components/Canary/minimal.tsx, src/components/Hypothesis/EvidenceSection/index.tsx
=> fix: fix scroll issues and footer on health modal

src/components/Layout/SidebarLayout.tsx
=> fix: add link to dashboard icon to home

src/components/Canary/Canary.stories.jsx, src/components/Connections/ConnectionForm.tsx, src/components/Connections/ConnectionsList.tsx, src/components/Connections/connectionTypes.tsx
=> 1149 add new connection forms

src/api/query-hooks/index.ts, src/api/services/configs.ts, src/components/Canary/Canary.stories.jsx, src/components/CollapsiblePanel/index.tsx, src/components/ConfigChanges/index.tsx, src/components/ConfigInsights/index.tsx, src/components/Insights/Insights.tsx, src/components/Insights/cells/ConfigInsightAgeCell.tsx, src/components/Insights/cells/ConfigInsightNameCell.tsx
=> fix: add pagination support for config insights panel

src/components/JobsHistory/JobsHistoryTableColumn.tsx
=> fix: disable sort by name in job history table

package-lock.json, package.json, pages/global.css, src/components/ConfigChanges/index.tsx, src/components/ConfigDetailsChanges/ConfigDetailsChanges.tsx, src/components/DiffRenderer/DiffRenderer.tsx
=> feat: add diff renderer component & integrated into the config change popup

src/components/Forms/SpecEditorForm.tsx, src/components/SpecEditor/SpecEditor.tsx
=> fix: add back button for config scrapper & health check forms

src/components/ConfigLink/ConfigLink.tsx, src/components/TopologyConfigLinkModal/TopologyConfigLinkModal.tsx
=> fix: fixed config icons missing issue on configs panel

src/components/JobsHistory/JobsHistoryTable.tsx, src/components/JobsHistory/JobsHistoryTableColumn.tsx, src/components/SchemaResourcePage/SchemaResourceList.tsx
=> fix: fixed job history styling issue & code refactor

src/api/query-hooks/index.ts, src/api/services/topology.ts, src/components/Agents/AgentNamesDropdown.tsx, src/pages/TopologyPage.tsx
=> feat: add support for topology filtering by agent

src/components/ActionLink/ActionLink.tsx, src/components/Changelog/IncidentChangelog.tsx, src/components/Changelog/IncidentChangelogItems.tsx, src/components/ConfigChanges/Cells/ConfigChangeAgeCell.tsx, src/components/ConfigDetailsChanges/ConfigDetailsChanges.tsx, src/components/ConfigLink/ConfigLink.tsx, src/components/CostDetails/CostDetails.tsx, src/components/DescriptionCard/index.tsx, src/components/DetailsTable/DetailsTable.tsx, src/components/Dropdown/ComponentTypesDropdown/index.tsx, src/components/Dropdown/DropdownWithActions.tsx, src/components/Dropdown/SubtleDropdown.tsx, src/components/IncidentDetails/IncidentDetailsPanel.tsx, src/components/Incidents/IncidentStatusDropdown.tsx, src/components/Incidents/IncidentTypeDropdown.tsx, src/components/IncidentsFilterBar/index.tsx, src/components/Insights/cells/ConfigInsightAgeCell.tsx, src/components/Insights/cells/ConfigInsightNameCell.tsx, src/components/ReactSelectDropdown/index.tsx, src/components/RefreshDropdown/index.tsx, src/components/SearchableDropdown/index.jsx, src/components/Sidebars/incidents.tsx, src/components/TopologyCard/Property.tsx, src/components/TopologyConfigChanges/index.tsx, src/components/TopologyDetails/index.tsx, src/components/TopologyLink/index.tsx, src/components/TopologySidebar/ComponentTeamLink.tsx
=> fix: update dropdowns & sidebar panels content font styles

src/components/StatusLine/StatusLine.tsx
=> fix: status line label wrap issue fix

src/components/ConfigLink/ConfigLink.tsx, src/components/Sidebars/configs.tsx
=> fix: config link name wrap issue fix

src/components/ConfigSidebar/ConfigDetails.tsx, src/components/DescriptionCard/index.tsx, src/components/IncidentDetails/IncidentDetailsPanel.tsx, src/components/IncidentDetails/IncidentDetailsRow.tsx, src/components/TopologyDetails/index.tsx, src/constants/index.ts
=> feat: switch details panel label to top lable style

src/api/query-hooks/index.ts, src/api/services/topology.ts, src/components/Canary/HealthCheckEdit/index.tsx, src/components/Dropdown/ComponentTypesDropdown/index.tsx, src/components/FilterLogs/LogsSelector.tsx, src/components/TopologyBreadcrumbs/index.tsx, src/components/TopologyCard/index.tsx, src/context/TopologyPageContext.tsx, src/pages/TopologyPage.tsx
=> 983-topology-health-filter-doesnt-cover-possibilities

src/App.tsx, src/api/schemaResources.ts, src/components/EventQueueStatus/EventQueueStatusList.tsx, src/components/EventQueueStatus/eventQueue.ts, src/pages/Settings/ConnectionsPage.tsx, src/pages/Settings/EventQueueStatus.tsx, src/pages/Settings/FeatureFlagsPage.tsx, src/pages/Settings/LogBackendsPage.tsx, src/services/permissions/features.ts
=> 1164-event-queue-status-pages

src/components/IncidentDetails/ResponderTypes/Jira/index.tsx, src/components/IncidentDetails/ResponderTypes/MicrosoftPlanner/index.tsx
https://github.com/flanksource/flanksource-ui/issues/1218
=> fix: responder config types

src/components/SpecEditor/HealthSpecEditor.tsx, src/components/SpecEditor/SpecEditor.tsx
Resolves: https://github.com/flanksource/flanksource-ui/issues/1253
=> fix: save button in health check from

src/components/JobsHistory/Filters/JobsHistoryFilters.tsx
Resolves: https://github.com/flanksource/flanksource-ui/issues/1248
=> feat: add missing job history statuses in the filter

src/api/services/incident.ts, src/components/IncidentDetails/IncidentDetailsPanel.tsx, src/components/Incidents/IncidentList/index.tsx
Closes #1098
[Loom Video](https://www.loom.com/share/d4fa115700b04fd1aec0c59bda6f3e0f)
=> FLNK-1098 - Show new incident id 

src/components/Forms/Health/ICMPHealthFormEditor.tsx, src/components/SpecEditor/HealthSpecEditor.tsx
=> feat: add icmp type health check form

src/components/Forms/Formik/FormikCodeEditor.tsx, src/components/Forms/Health/AlertmanagerHealthFormEditor.tsx, src/components/Forms/Health/ElasticsearchHealthFormEditor.tsx, src/components/Forms/Health/ExecHealthFormEditor.tsx, src/components/Forms/Health/TCPHealthFormEditor.tsx, src/components/SpecEditor/HealthSpecEditor.tsx
Fixes: https://github.com/flanksource/flanksource-ui/issues/1150
=> chore: add missing health form options for canary

src/api/services/configs.ts
Fixes: https://github.com/flanksource/flanksource-ui/issues/1238
=> chore: add sorting order to configs side panel

package-lock.json, package.json, src/components/TopologyFilters/TopologyFilterBar.tsx, src/pages/TopologyPage.tsx
=> 1233-topology-navigation-progress-bar

src/api/services/IncidentsHistory.ts, src/components/Avatar/index.tsx, src/components/Changelog/EvidenceChangelogContent.tsx, src/components/Changelog/IncidentHistoryItemTypeContent.tsx
Resolves: https://github.com/flanksource/flanksource-ui/issues/1257
Resolves: https://github.com/flanksource/flanksource-ui/issues/1251
=> feat: fix empty incident changelog

src/api/query-hooks/index.ts, src/api/services/configs.ts, src/components/TopologyConfigLinkModal/TopologyConfigLinkModal.tsx, src/components/TopologySidebar/TopologyActionBar.tsx, src/pages/config/ConfigList.tsx
=> 1271-full-config-listing-requested-navigating-topology

src/api/query-hooks/index.ts, src/api/services/configs.ts, src/components/ConfigAnalysisLink/ConfigAnalysisLink.tsx, src/components/ConfigAnalysisLink/ConfigInsightsDetailsModal.tsx, src/components/ConfigInsights/index.tsx, src/components/Insights/Insights.tsx, src/components/Insights/cells/ConfigInsightAgeCell.tsx, src/components/Insights/cells/ConfigInsightNameCell.tsx, src/components/TopologyCard/TopologyConfigAnalysisLine.tsx, src/components/TopologySidebar/TopologyInsights.tsx
=> fix: fix topology insights not loading

src/components/Canary/CanaryPopup/CheckTitle.tsx, src/components/Canary/renderers.tsx, src/components/Hypothesis/EvidenceSection/index.tsx, src/components/Modal/index.tsx, src/components/Status/index.tsx
=> 1266-overflow-health-modal-handled-better-title-long

src/components/FilterLogs/LogsSelector.tsx, src/components/Logs/Table/LogsTable.tsx
=> 1240-log-selection-retained-selecting-new-component

src/components/StatusLine/StatusLine.tsx, src/components/TopologyCard/TopologyConfigAnalysisLine.tsx, src/components/TopologyCard/index.tsx, src/context/TopologyPageContext.tsx
=> 1279-analysis-component-called-every-topology-item

src/components/ConfigAnalysis/ConfigInsightsList.tsx, src/components/ConfigAnalysisLink/ConfigInsightsDetailsModal.tsx
=> fix: fix incorrect props passed to ConfigInsightsDetails Modal

src/api/services/incident.ts, src/components/FilterIncidents/FilterIncidents.tsx, src/components/Incidents/IncidentList/incidenttList.stories.tsx, src/components/OptionsList/OptionsList.stories.tsx, src/components/RadioOptionsGroup/index.tsx, src/components/RefreshDropdown/index.tsx, src/components/SearchSelect/SearchSelect.stories.tsx, src/components/SearchSelect/index.tsx, src/components/SearchSelectTag/SearchSelectTag.stories.tsx, src/components/SearchSelectTag/index.tsx, src/components/SearchableDropdown/SearchableDropdown.stories.tsx, src/components/SearchableDropdown/index.tsx, src/pages/incident/IncidentListPage.tsx
=> 1298-default-incidents-filter-open

src/components/ConfigListToggledDeletedItems/ConfigListToggledDeletedItems.tsx, src/components/ConfigsListFilters/index.tsx, src/components/Switch/index.tsx, src/pages/config/ConfigList.tsx
=> 1283-hide-deleted-configs-preference-not-saved

src/api/services/responder.ts, src/components/IncidentDetails/Responders.tsx, src/components/TopologyConfigLinkModal/TopologyConfigLinkModal.tsx
=> 1281-reflash-insights-count-sidebar-new-config-linked-componenttopology

src/api/query-hooks/index.ts, src/api/services/configs.ts, src/components/ConfigLink/ConfigLink.tsx, src/components/ConfigList/Cells/ConfigListCostCell.tsx, src/components/ConfigList/Cells/ConfigListDateCell.tsx, src/components/ConfigList/Cells/ConfigListNameCell.tsx, src/components/ConfigList/Cells/ConfigListTypeCell.tsx, src/components/ConfigList/ConfigListColumn.tsx, src/components/ConfigList/index.tsx, src/components/ConfigSummary/ConfigSummaryList.tsx, src/components/ConfigTypesDropdown/index.tsx, src/components/Configs/ConfigsTypeIcon.tsx, src/components/ConfigsListFilters/index.tsx, src/components/DataTable/index.tsx, src/components/GroupByDropdown/index.tsx, src/components/Tabs/TabbedLinks.tsx, src/pages/config/ConfigList.tsx
=> 1166-config-list-switch-new-config-summary-view

src/api/schemaResources.ts, src/api/services/configs.ts, src/api/services/evidence.ts
=> 1308-remove-queries-configs-analysis

src/components/ConfigDetailsChanges/ConfigDetailsChanges.tsx, src/components/ConfigLink/ConfigLink.tsx, src/pages/config/ConfigChangesPage.tsx
=> fix: fix config change modal title being cut off

src/api/query-hooks/health.tsx, src/api/services/topology.ts, src/components/Canary/CanaryPopup/CheckDetails.tsx, src/components/Canary/CanaryPopup/utils.ts, src/components/Canary/CanaryStatusChart/index.tsx
=> 1239-health-check-dialog-uptime-latency-metrics-not-updated-changing-duration

src/components/TopologyCard/TopologyDropdownMenu.tsx, src/components/TopologyConfigLinkModal/TopologyConfigLinkModal.tsx
=> fix: fix link to topology dropdown item click not working

src/components/Icon/index.tsx
=> fix: fix missing icons for certain connections types

src/api/query-hooks/useComponentConfigChanges.ts, src/api/services/configs.ts, src/components/ConfigChanges/index.tsx, src/components/ConfigDetailsChanges/ConfigDetailsChanges.tsx, src/components/TopologyConfigChanges/index.tsx
=> fix: show modal on click component details inside panel

src/App.tsx, src/api/query-hooks/useConfigAnalysisQuery.ts, src/api/services/configs.ts, src/api/services/topology.ts, src/components/ConfigAnalysis/ConfigInsightsList.tsx, src/components/ConfigAnalysis/Filters/ConfigInsightsFilters.tsx, src/components/ConfigsPage/ConfigTabsLinks.tsx, src/components/Dropdown/ComponentNamesDropdown/index.tsx, src/components/IncidentCardSummary/index.tsx, src/components/Incidents/data.tsx, src/components/TopologyCard/TopologyConfigAnalysisLine.tsx, src/pages/config/ConfigDetailsChangesPage.tsx, src/pages/config/ConfigDetailsInsightsPage.tsx
Blocked - Component Field doesn't exist in config analysis view
Closes #1307 & Closes #1321
=> 1307-config-details-insights-tab

src/components/ConfigAnalysisLink/ConfigAnalysisLink.tsx, src/components/Insights/Insights.tsx, src/components/Insights/cells/ConfigInsightNameCell.tsx
=> chore: remove config insight side panel tooltip

pages/_app.tsx, pages/index.tsx, src/App.tsx, src/components/Layout/SidebarLayout.tsx
=> 1323-cannot-see-contents-settings-left-sidebar-screen-small

src/components/Authentication/AuthProviderWrapper.tsx, src/components/Authentication/Clerk/ClerkAuthContextProvider.tsx, src/components/Authentication/Kratos/KratosAuthContextProvider.tsx, src/components/Forms/Formik/FormikAuthFields.tsx
useOrganizations is only available under clerk content and not available for kratos
=> fix: fix switch between clerk and kratos not working

src/components/IncidentDetails/AddResponders/AddResponderModal.tsx
@adityathebe please confirm this fixes the issue blocking you
=> fix: fix add team responder going to 1st step after selecting responder type

src/components/Layout/SidebarLayout.tsx
=> fix: fix main menu item not being padded

src/App.tsx, src/api/query-hooks/playbooks.tsx, src/api/services/playbooks.ts, src/components/Playbooks/Settings/PlaybookSpecsForm.tsx, src/components/Playbooks/Settings/PlaybookSpecsTable.tsx, src/pages/Settings/PlaybookSettingsPage.tsx, src/services/permissions/features.ts
@moshloop Currently blocked from being tested it seems like the latest changes with the playbooks table haven't been deployed, will chat with Yash to help me here.
Closes #1352
=> feat: add settings page to manage playbooks specs

package-lock.json, package.json, src/App.tsx, src/api/query-hooks/useNotificationsQuery.ts, src/api/services/notifications.ts, src/api/services/teams.ts, src/api/services/users.ts, src/components/Forms/Formik/FormikConfigFormFieldsArray.tsx, src/components/Forms/Formik/FormikConfigFormFormsArray.tsx, src/components/Forms/Formik/FormikConnectionField.tsx, src/components/Forms/Formik/FormikNotificationEventsDropdown.tsx, src/components/Forms/Formik/FormikNotificationsTemplateField.tsx, src/components/Forms/Formik/FormikPeopleDropdown.tsx, src/components/Forms/Formik/FormikSelectDropdown.tsx, src/components/Forms/Formik/FormikTeamsDropdown.tsx, src/components/Forms/Notifications/NotificationConfigurationForm.tsx, src/components/Forms/Notifications/NotificationsRecipientsTabs.tsx, src/components/JobsHistory/JobHistoryStatusColumn.tsx, src/components/JobsHistory/JobsHistoryTableColumn.tsx, src/components/Notifications/EditNotification.tsx, src/components/Notifications/NotificationsForm.tsx, src/components/Notifications/NotificationsSettingsPage.tsx, src/components/Notifications/NotificationsTable.tsx, src/components/Notifications/notificationsTableColumns.tsx, src/components/SchemaResourcePage/SchemaResourceList.tsx, src/components/SchemaResourcePage/resourceTypes.tsx, src/services/permissions/features.ts
=> feat: add page and form for notifications

next.config.js
=> Fix Docker Image Building Failing

src/App.tsx, src/components/AttachEvidenceDialog/AttachAsEvidenceDialogButton.tsx, src/components/Canary/minimal.tsx, src/components/ConfigAnalysisLink/ConfigInsightsDetailsModal.tsx, src/components/ConfigDetailsChanges/ConfigDetailsChanges.tsx, src/components/ConfigSidebar/ConfigActionBar.tsx, src/components/Logs/Table/LogsTable.tsx, src/components/SchemaResourcePage/resourceTypes.tsx, src/components/Sidebars/incidents.tsx, src/components/TopologyCard/TopologyDropdownMenu.tsx, src/components/TopologySidebar/TopologyActionBar.tsx, src/context/FeatureFlagsContext.tsx, src/services/permissions/features.ts
=> Disabled Incidents and Logs Features using Feature Flags

src/api/services/configs.ts, src/components/ConfigChangeHistory/index.tsx, src/components/ConfigDetailsChanges/ConfigChangeDetailsSection.tsx, src/components/ConfigDetailsChanges/ConfigDetailsChanges.tsx, src/components/ConfigLink/ConfigLink.tsx, src/components/DescriptionCard/index.tsx, src/components/Modal/index.tsx, src/components/TopologyConfigChanges/index.tsx
=> fix: config change modal ui improvements

src/App.tsx, src/api/query-hooks/index.ts, src/components/Notifications/NotificationsSettingsPage.tsx, src/context/TopologyPageContext.tsx, src/pages/TopologyPage.tsx, src/query-client.ts
=> 1334-config-list-filtering-ignores-type-selection

src/components/Authentication/Kratos/KratosAuthSessionChecker.tsx, src/components/SchemaResourcePage/SchemaResourceEdit.tsx
=> 967-settings-health-clicking-config-source-crashes-ui

src/utils/date.ts
=> fix: don't return relative date if it's 0001-01-01T00:00:00+00:00

src/api/schemaResources.ts, src/components/DataTable/DataTableRow.tsx, src/components/Incidents/IncidentList/IncidentListColumns.tsx, src/components/ManageUserRoles/ManageUserRoles.tsx, src/pages/Settings/LogBackendsPage.tsx
=> 1204-overflow-issues-table-select-widget

src/components/Authentication/Kratos/KratosAuthSessionChecker.tsx, src/components/Authentication/Kratos/KratosLogin.tsx, src/components/Modal/index.tsx
=> 1408-kratos-login-requires-login-twice

src/pages/TopologyPage.tsx
=> fix: fix topology sorting is not working

src/pages/config/ConfigList.tsx
=> fix: fix catalog breadcrumb throwing error when type is clicked

src/components/ConfigDetailsChanges/ConfigDetailsChanges.tsx, src/components/ConfigLink/ConfigLink.tsx, src/components/Forms/Connection/SFTPConnectionFormEditor.tsx, src/components/Forms/Connection/SMBConnectionFormEditor.tsx, src/components/Forms/Formik/FormikAuthFields.tsx, src/components/Forms/Formik/FormikConfigEnvVarFields.tsx, src/components/Forms/Health/AlertmanagerHealthFormEditor.tsx, src/components/Forms/Health/ElasticsearchHealthFormEditor.tsx, src/components/Forms/Health/HTTPHealthFormEditor.tsx, src/components/Forms/Health/MongoHealthFormEditor.tsx, src/components/Forms/Health/RedisHealthFormEditor.tsx, src/components/Modal/ModalTitleListItems.tsx, src/components/RadioOptionsGroup/index.tsx, src/components/SchemaResourcePage/AddSchemaResourceModal.tsx, src/components/SchemaResourcePage/index.tsx, src/components/SpecEditor/HealthSpecEditor.tsx, src/components/Switch/index.tsx, src/pages/health.tsx
=> feat: add redis and mongo forms

src/components/Chip/chip.tsx, src/components/IncidentCardSummary/index.tsx, src/components/Incidents/data.tsx, src/components/StatusLine/StatusLine.tsx, src/components/TopologyCard/TopologyConfigAnalysisLine.tsx, src/context/TopologyPageContext.tsx
=> 1335-summary-mismatch-components-dashboard

src/api/services/incident.ts, src/components/AttachEvidenceDialog/index.tsx, src/components/Dropdown/ComponentTypesDropdown/index.tsx, src/components/Dropdown/SelectDropdown.tsx, src/components/Incidents/IncidentCreate/index.tsx, src/components/TopologyFilters/TopologyFilterBar.tsx
=> 1351-dropdowns-fixed-height

package-lock.json, package.json, src/components/Canary/minimal.tsx, src/components/ConfigItem/index.tsx, src/components/Playbooks/Runs/SelectPlaybookToRun.tsx, src/components/Playbooks/Runs/SubmitPlaybookRunForm.tsx
=> 1429-run-playbooks-health-checks

src/App.tsx, src/api/query-hooks/playbooks.tsx, src/api/services/playbooks.ts, src/components/Icon/index.tsx, src/components/Playbooks/Runs/PlaybookRunsActionItem.tsx, src/components/Playbooks/Runs/PlaybookRunsActions.stories.tsx, src/components/Playbooks/Runs/PlaybookRunsActions.tsx, src/components/Playbooks/Runs/PlaybookRunsList.tsx, src/components/Playbooks/Runs/PlaybookRunsPageTabs.tsx, src/components/Playbooks/Runs/PlaybookRunsSidePanel.tsx, src/components/Playbooks/Runs/PlaybookRunsStatus.tsx, src/components/Playbooks/Runs/PlaybooksActionsResults.stories.tsx, src/components/Playbooks/Runs/PlaybooksActionsResults.tsx, src/pages/playbooks/PlaybookRuns.tsx, src/pages/playbooks/PlaybookRunsDetails.tsx, src/pages/playbooks/PlaybooksList.tsx, src/services/permissions/features.ts, src/utils/date.ts
=> feat: add playbook runs page

src/components/Dropdown/SubtleDropdown.tsx, src/components/TopologyCard/Property.tsx, src/components/TopologyCard/Utils/FormatProperties.tsx, src/components/TopologyDetails/index.tsx, src/context/TopologyPageContext.tsx
Refactored the FormatProperty component for performance by moving all the calculations to useMemo and making it easier to understand.
Closes #1391
=> 1391-memory-cpu-formatting-issues

src/api/services/playbooks.ts, src/components/Playbooks/Runs/SelectPlaybookToRun.tsx, src/components/Playbooks/Runs/SubmitPlaybookRunForm.tsx, src/components/Playbooks/Settings/PlaybookSpecsForm.tsx, src/components/Playbooks/Settings/PlaybookSpecsTable.tsx
This will temporarily break submit playbook run submissions, but the issue was fixed [here](https://github.com/flanksource/duty/pull/289) and once deployed, should be working as expected.
Closes #1435
=> fix: fix error saving playbook spec due to ID field

next.config.js, src/api/services/evidence.ts, src/api/services/hypothesis.ts, src/components/Canary/table.tsx, src/components/Dropdown/DropdownWithActions.stories.tsx, src/components/Hypothesis/Comments/index.tsx, src/components/Hypothesis/EvidenceSection/EvidenceSection.stories.tsx, src/components/Hypothesis/EvidenceSection/index.tsx, src/components/Hypothesis/HypothesisBar/HypothesisBar.stories.tsx, src/components/Hypothesis/HypothesisBar/index.tsx, src/components/Hypothesis/HypothesisCommentsViewContainer/HypothesisCommentsViewContainer.tsx, src/components/Hypothesis/HypothesisDetails/index.tsx, src/components/Hypothesis/HypothesisNode/HypothesisNode.stories.tsx, src/components/Hypothesis/StatusDropdownContainer/index.tsx, src/components/IncidentCard/IncidentCard.tsx, src/components/IncidentCardSummary/index.tsx, src/components/IncidentDetails/DefinitionOfDone/EvidenceView/index.tsx, src/components/Playbooks/Runs/PlaybookRunsActions.stories.tsx, src/components/Playbooks/Runs/PlaybookRunsSidePanel.tsx, src/components/SearchSelect/index.tsx, src/hooks/useHypothesisStatusForm.ts
This should help us catch some of the regression that occur when data shape changes and have an overall stable product.
- Fixed most of the errors
- Added the @ts-expect-error directive to allow us to fix this ones in the future when we have the bandwidth
=> Fix All Typescript Type Issue and Stop Ignoring Typescript Errors

src/api/services/topology.ts, src/components/HealthChecks/CheckLink.tsx, src/components/HealthChecks/__tests__/CheckLink.unit.test.tsx, src/components/Status/HealthCheckStatus.story.tsx, src/components/Status/HealthCheckStatus.tsx, src/components/Status/__tests__/HealthCheckStatus.unit.test.tsx, src/components/TopologySidebar/ComponentChecks.tsx, src/components/TopologySidebar/TopologySidebar.tsx
=> feat: add side panel for components checks list

src/components/GroupByDropdown/__tests__/GroupByDropdown.unit.test.tsx, src/components/GroupByDropdown/index.tsx, src/pages/config/ConfigList.tsx
=> fix: sort group by for catalog alphabetically

src/components/Connections/ConnectionForm.tsx, src/components/Connections/connectionTypes.tsx
=> fix: fix type value should always in lower case

src/components/Forms/Formik/FormikCodeEditor.tsx, src/components/Forms/Formik/FormikSelectDropdown.tsx
=> 1400-notifications-template-left-empty-saved

src/api/query-hooks/index.ts, src/api/services/configs.ts, src/components/Insights/Insights.tsx
=> fix: fix incorrect count for topology insight

src/components/Agents/AgentName.tsx, src/components/CustomScroll/index.tsx, src/components/HealthChecksSummary/index.tsx, src/components/HealthSummary/summary.tsx, src/components/TopologyCard/Property.tsx, src/components/TopologyCard/TopologyCard.stories.tsx, src/components/TopologyCard/index.tsx, src/context/TopologyPageContext.tsx
=> 1446-topology-add-statusreason-subtitle-header

package-lock.json, package.json, src/components/JSONViewer/index.tsx
=> 1441-canary-spec-field-hide-line-nos

.eslintrc.js, src/api/services/configs.ts, src/components/Configs/Sidebar/ConfigActionBar.tsx, src/components/Configs/Sidebar/ConfigDetails.tsx, src/components/Configs/Sidebar/ConfigSidebar.tsx, src/components/Configs/Sidebar/__tests__/ConfigDetails.unit.test.tsx, src/components/Utils/DisplayDetailsRow.tsx, src/components/Utils/__tests__/DisplayDetailsRow.unit.test.tsx, src/pages/config/ConfigDetailsChangesPage.tsx, src/pages/config/ConfigDetailsPage.tsx
=> 1386-config-tagdetails-panel-add-type

src/api/services/topology.ts, src/components/TopologyDetails/index.tsx
=> feat: add Topology details to component details panel

src/components/Forms/SpecEditorForm.tsx
=> fix: show name field for custom health checks

src/components/Canary/Canary.stories.tsx, src/components/Canary/CanaryTabs.tsx, src/components/Canary/FilterForm/index.jsx, src/components/Canary/index.tsx, src/components/Tabs/Tabs.tsx, src/pages/health.tsx
=> 1476-overflow-issue-side-panel-canary-smaller-screen

src/components/Canary/grouping.ts
=> fix: fix / name grouped children being incomplete

src/components/Canary/CanaryTabs.tsx, src/components/Tabs/Tabs.tsx
=> 1485-sort-canary-tabs-alphabetically

src/components/Forms/Formik/FormikConnectionField.tsx, src/components/Forms/Formik/FormikSelectDropdown.tsx
=> fix: add connection type icons to the dropdown

src/components/TagList/TagList.tsx, src/components/TagList/__tests__/TagList.unit.test.tsx
=> feat: sort tags by account, namespace, name and the rest

src/components/TopologyCard/index.tsx
=> fix: fix issue where the card content would overflow

src/components/TristateToggle/index.tsx
=> fix: fix the tri-state button not moving with content when scrolling

src/components/JobsHistory/JobsHistoryTableColumn.tsx, src/components/JobsHistory/__tests__/JobsHistoryTable.unit.test.tsx, src/utils/__tests__/date.unit.test.ts, src/utils/date.ts
=> fix: fix job history duration formatting issue

src/components/Agents/AgentName.tsx, src/components/Badge/index.tsx, src/components/TopologyCard/CardMetrics.tsx, src/components/TopologyCard/Property.tsx, src/components/TopologyCard/Utils/FormatProperties.tsx, src/components/TopologyCard/index.tsx, src/components/TopologyDetails/index.tsx, src/ui/stats/ProgressBar.stories.tsx, src/ui/stats/ProgressBar.tsx
=> 1477-gauge-property-renderer

package-lock.json, package.json, src/components/Authentication/Clerk/ClerkAuthSessionChecker.tsx, src/components/Authentication/Clerk/ClerkLogin.tsx, src/components/Authentication/Clerk/ClerkRegistration.tsx
@moshloop this should safe guard in a situation where the abandons the sign-up before creating an organization and comes backs later, the flow should be much better now.
=> Improve-clerk-auth

src/api/types/configs.ts, src/api/types/topology.ts, src/components/Configs/Sidebar/ConfigDetails.tsx, src/components/Configs/Sidebar/Utils/__tests__/formatConfigTags.unit.test.tsx, src/components/Configs/Sidebar/Utils/formatConfigTags.tsx, src/components/Configs/Sidebar/__tests__/ConfigDetails.unit.test.tsx, src/components/Topology/Sidebar/ComponentChecks.tsx, src/components/Topology/Sidebar/ComponentTeamLink.tsx, src/components/Topology/Sidebar/ComponentTeams.tsx, src/components/Topology/Sidebar/TopologyActionBar.tsx, src/components/Topology/Sidebar/TopologyDetails.tsx, src/components/Topology/Sidebar/TopologyInsights.tsx, src/components/Topology/Sidebar/TopologySidebar.tsx, src/components/Topology/Sidebar/Utils/__tests__/formatTopologyProperties.unit.test.tsx, src/components/Topology/Sidebar/Utils/formatTopologyProperties.tsx, src/components/Topology/Sidebar/__tests__/TopologyDetails.unit.test.tsx, src/components/TopologyCard/CardMetrics.tsx, src/components/TopologyCard/TopologyDropdownMenu.tsx, src/components/Utils/DisplayGroupedProperties.tsx, src/components/Utils/__tests__/DisplayGroupedProperties.unit.test.tsx, src/pages/TopologyPage.tsx
=> 1510-topology-property-improvements

src/components/Canary/CanaryPopup/CheckDetails.tsx
=> fix: use an appropriate runtime if check is older than 1h

package-lock.json, package.json, src/api/services/configs.ts, src/components/Canary/CanaryTableColumns.tsx, src/components/QueryBuilder/index.tsx
=> 1543-uptime-count-should-be-all-those-not-100-not-all-those-0

src/components/Playbooks/Runs/Submit/PlaybooksDropdownMenu.tsx
=> fix: fix playbook dropdown going under the bg

src/components/Canary/index.tsx, src/components/TristateToggle/index.tsx
=> 1550-we-may-have-a-race-condition-when-setting-url-params-for-health-page-in-mission-control-may-impact-performance-and-ux

src/components/Connections/ConnectionsList.tsx, src/components/Connections/connectionTypes.tsx
=> 1567-missing-icons-in-connections-page

pages/global.css, src/components/DataTable/index.tsx
=> fix: fix table content scrolling below sticky header

src/components/Button/index.tsx, src/components/Forms/Formik/FormikCodeEditor.tsx, src/components/Forms/SpecEditorForm.tsx
=> Fix Spec Editor - 2-way mapping is broken 

src/api/query-hooks/health.tsx, src/api/query-hooks/playbooks.tsx, src/components/Canary/CanaryPopup/CheckDetails.tsx, src/components/Canary/CanaryStatusChart/index.tsx
=> 1561-Failed-to-fetch-checks-data-when-a-health-check-graph-doesnt-return-values

src/api/schemaResources.ts, src/components/SchemaResourcePage/SchemaResourceList.tsx
=> feat: add agent and namespace columns to the topologies table

src/components/Authentication/Kratos/KratosLogin.tsx, src/components/Authentication/Kratos/KratosRecovery.tsx, src/components/ory/ui/Flow.tsx
=> 1612-Recover-account-is-broken

src/api/schemaResources.ts, src/components/JobsHistory/JobHistoryStatusColumn.tsx, src/components/SchemaResourcePage/SchemaResourceList.tsx
=> 1578-Health-check-settings-page-improvements

src/components/Configs/ConfigTypesDropdown/index.tsx, src/components/GroupByDropdown/index.tsx, src/components/TagList/TagList.tsx
=> fix: fix config page crashing due to non null check for localeCompare

src/components/Topology/Sidebar/TopologyDetails.tsx
=> fix: show correct creating toplogy name instead of topology

src/components/Forms/Formik/FormikSelectDropdown.tsx, src/components/Playbooks/Runs/Submit/PlaybookRunParams.tsx, src/components/Playbooks/Runs/Submit/PlaybookSelectResource.tsx
=> 1643-Dropdown-menu-text-should-be-smaller

src/components/Agents/InstalAgentInstruction/CLIInstallAgent.tsx, src/components/Agents/InstalAgentInstruction/FluxInstallAgent.tsx, src/components/Agents/InstalAgentInstruction/__tests__/CLIInstallAgent.unit.test.tsx
=> fix: use browser url instead of backend url for agent host name

src/components/Forms/Configs/AWSConfigsFormEditor.tsx, src/components/Forms/Configs/AzureConfigsFormEditor.tsx, src/components/Forms/Configs/AzureDevopsConfigsFormEditor.tsx, src/components/Forms/Configs/ConfigRentionSpec.tsx, src/components/Forms/Configs/FileConfigsFormEditor.tsx, src/components/Forms/Configs/GithubActionsConfigsFormEditor.tsx, src/components/Forms/Configs/HttpConfigsFormEditor.tsx, src/components/Forms/Configs/KubernetesConfigsFormEditor.tsx, src/components/Forms/Configs/KubernetesFileConfigsFormEditor.tsx, src/components/Forms/Configs/SQLConfigsFormEditor.tsx, src/components/Forms/Configs/TrivyConfigsFormEditor.tsx, src/components/Forms/Configs/__tests__/ConfigRentionSpec.unit.test.tsx, src/components/SpecEditor/ConfigScrapperSpecEditor.tsx
=> feat: add retention fields for configs for specs

src/api/query-hooks/playbooks.tsx, src/api/services/playbooks.ts, src/components/Playbooks/Runs/Actions/PlaybookRunsActions.tsx, src/components/Playbooks/Runs/PlaybookRunsList.tsx, src/components/Playbooks/Runs/PlaybookRunsSidePanel.tsx, src/components/Playbooks/Runs/Submit/PlaybooksDropdownMenu.tsx, src/components/Playbooks/Runs/Submit/SubmitPlaybookRunForm.tsx, src/components/Playbooks/Runs/Submit/__tests__/SelectPlaybookToRun.unit.test.tsx, src/components/Playbooks/Runs/Submit/__tests__/SubmitPlaybookRunForm.unit.test.tsx, src/components/Playbooks/Settings/PlaybookSpecCard.tsx, src/components/Playbooks/Settings/PlaybookSpecIcon.tsx, src/pages/playbooks/PlaybookRuns.tsx, src/pages/playbooks/PlaybookRunsDetails.tsx
=> feat: use playbook icons

src/components/Playbooks/Runs/Actions/PlaybookRunsActions.tsx
=> fix: show scheduled time, when in the future

netlify.toml, package-lock.json, package.json, src/components/CodeEditor/index.tsx
Trying the following workaround -> https://github.com/netlify/next-runtime/issues/2385#issuecomment-1911785301
Fixes #1515
=> chore: update next to v14 latest to test work around

src/components/Connections/connectionTypes.tsx, src/components/Layout/SidebarLayout.tsx
=> feat: add folder connection type

package-lock.json, package.json, src/components/Agents/Add/AddAgentForm.tsx, src/components/Agents/InstalAgentInstruction/CLIInstallAgent.tsx, src/components/Agents/InstalAgentInstruction/FluxInstallAgent.tsx, src/components/Agents/InstalAgentInstruction/InstallAgentModal.tsx, src/components/Agents/InstalAgentInstruction/__tests__/CLIInstallAgent.unit.test.tsx, src/components/Agents/InstalAgentInstruction/__tests__/FluxInstallAgent.unit.test.tsx, src/components/Forms/Formik/FormikAutocompleteDropdown.tsx, src/components/Forms/Formik/FormikKeyValueMapField.tsx, src/components/Forms/Formik/FormikSwitchField.tsx, src/components/Forms/Formik/FormikTextInput.tsx, src/ui/CodeBlock/CodeBlock.tsx
=> 1576-Display-usernamepassword-correctly-when-creating-an-agent

src/components/Topology/TopologyPage/TopologyFilterBar.tsx, src/components/Topology/TopologyPopover/topologySort.tsx, src/pages/TopologyPage.tsx
=> 1591-Sorting-by-component-property-does-not-take-effect-immiedatly

src/api/schemaResources.ts, src/components/EventQueueStatus/EventQueueStatusList.tsx, src/components/EventQueueStatus/eventQueue.ts, src/pages/Settings/EventQueueStatus.tsx
=> feat: switch to event_queue_summary view for event queue

.gitignore, src/api/services/topology.ts, src/components/Canary/CanaryInterface.tsx, src/components/Canary/CanaryPopup/CheckDetails.tsx, src/components/Canary/CanaryPopup/CheckRunNow.tsx, src/components/Canary/CanaryPopup/StatusHistory/StatusHistory.tsx, src/components/Canary/CanaryPopup/__tests__/CheckRunNow.unit.test.tsx, src/components/Canary/ChecksListing.tsx, src/components/Canary/index.tsx, src/context/UserAccessContext/UserAccessContext.tsx
=> 1675-Add-run-now-button-to-canary-checker-modal

src/components/JobsHistory/Filters/JobHistoryNames.tsx, src/components/JobsHistory/Filters/JobsHistoryFilters.tsx, src/components/JobsHistory/JobsHistorySettingsPage.tsx, src/ui/TimeRangePicker/TimeRangePickerBody.tsx, src/ui/TimeRangePicker/useTimeRangeParams.tsx
=> fix: fix duration filter not working

src/App.tsx, src/components/Layout/SidebarLayout.tsx
=> feat: hide settings for non admins

src/App.tsx, src/components/Layout/SidebarLayout.tsx
Reverts flanksource/flanksource-ui#1688
=> Revert "feat: hide settings for non admins"

src/components/Canary/CanaryPopup/CheckRelationships.tsx
=> fix: fix incorrect link to catalog item from check modal relationship

src/components/Playbooks/Runs/Actions/PlaybooksActionsResults.tsx, src/pages/playbooks/PlaybookRuns.tsx, src/pages/playbooks/PlaybookRunsDetails.tsx
=> 1689-The-playbook-action-log-should-wrap

src/components/Forms/Formik/FormikAutocompleteDropdown.tsx, src/components/Forms/Formik/FormikIconPicker.tsx, src/components/Forms/Formik/FormikMultiSelectListField.tsx, src/components/Forms/Formik/FormikSelectDropdown.tsx, src/components/Forms/SpecEditorForm.stories.tsx, src/components/Forms/SpecEditorForm.tsx, src/components/SpecEditor/ConfigScrapperSpecEditor.tsx, src/components/SpecEditor/HealthSpecEditor.tsx, src/components/SpecEditor/SpecEditor.stories.tsx, src/components/SpecEditor/SpecEditor.tsx, src/components/TextInput/index.tsx
=> Fix Issues Affecting Spec Saving and Editing

src/components/Configs/ConfigList/ConfigListColumn.tsx, src/components/Configs/ConfigList/index.tsx, src/components/Configs/ConfigsTypeIcon.tsx, src/components/DataTable/index.tsx, src/pages/config/details/ConfigDetailsRelionshipsPage.tsx
=> fix: group and sort config relationships by type and name

src/components/Configs/ConfigList/Cells/ConfigListCostCell.tsx, src/components/Configs/ConfigList/ConfigListColumn.tsx
=> fix: fix incorrect summarization of config cost in groups

src/api/types/topology.ts, src/components/HealthChecksSummary/index.tsx, src/components/HealthSummary/summary.tsx, src/components/Topology/TopologyCard/index.tsx
=> fix: fix health checks summary not showing in topology code

package-lock.json, package.json, src/components/Configs/ConfigListToggledDeletedItems/ConfigListToggledDeletedItems.tsx, src/components/Configs/ConfigsListFilters/index.tsx, src/ui/Popover/Popover.tsx
=> fix: fix popover for tags not being visible on click

src/components/Playbooks/Runs/Submit/PlaybookSelectResource.tsx, src/components/Playbooks/Runs/Submit/SubmitPlaybookRunForm.tsx, src/ui/Button/index.tsx
=> 1677-playbook-improvements

src/api/services/playbooks.ts
=> fix: the playbook actions should be sorted by the start_time column

src/components/BreadcrumbNav/ConfigsDetailsBreadCrumb.tsx, src/components/Configs/ConfigDetailsTabs.tsx, src/pages/config/ConfigChangesPage.tsx, src/pages/config/ConfigInsightsList.tsx
=> fix: update breadcrumb for insights and changes should reflect navigation path

src/api/services/playbooks.ts, src/components/Playbooks/Runs/Submit/PlaybookParamsFieldsRenderer.tsx, src/components/Playbooks/Runs/Submit/PlaybookRunParams.stories.tsx, src/components/Playbooks/Runs/Submit/PlaybookRunParams.tsx, src/components/Playbooks/Runs/Submit/SubmitPlaybookRunForm.tsx, src/components/Playbooks/Runs/Submit/__tests__/SubmitPlaybookRunForm.unit.test.tsx
=> feat: pull templated values for playbook params from API calls

src/components/JobsHistory/Filters/JobHistoryNames.tsx, src/components/JobsHistory/JobsHistoryTableColumn.tsx, src/components/JobsHistory/__tests__/JobsHistoryTable.unit.test.tsx, src/utils/common.ts
=> 1697-The-job-name-in-the-dropdown-and-the-table-should-probably-be-the-same

src/api/services/users.ts, src/components/VersionInfo/VersionInfo.tsx
=> fix: frontend version is static and is known at build time

src/components/Playbooks/Runs/Actions/PlaybookRunsActions.tsx, src/components/Playbooks/Runs/Actions/ShowParamaters/PlaybookPeopleLink.tsx, src/components/Playbooks/Runs/Actions/ShowParamaters/PlaybookTeamLink.tsx, src/components/Playbooks/Runs/Actions/ShowParamaters/ShowPlaybookRunsParams.tsx, src/components/Playbooks/Runs/Actions/ShowParamaters/ViewPlaybookParamsModal.tsx, src/components/Topology/TopologyLink/index.tsx, src/ui/Button/index.tsx
=> Add Playbook Action View Params

src/components/SchemaResourcePage/index.tsx
=> fix: add refresh button to health, topology settings pages

src/api/types/playbooks.ts, src/components/Forms/Formik/FormikCodeEditor.tsx, src/components/Playbooks/Runs/Submit/PlaybookParamsFieldsRenderer.tsx, src/components/Playbooks/Runs/Submit/PlaybookRunParams.tsx
=> 1753-Playbook-param-improvements

src/components/SchemaResourcePage/SchemaResourceList.tsx, src/components/SchemaResourcePage/index.tsx
=> fix: config db table column has overlaps and ui improvements

src/api/types/playbooks.ts, src/components/CodeEditor/index.tsx, src/components/Forms/Formik/FormikCodeEditor.tsx, src/components/Playbooks/Runs/Submit/PlaybookParamsFieldsRenderer.tsx, src/components/Playbooks/Runs/Submit/PlaybookRunParams.tsx, src/components/Playbooks/Runs/Submit/SubmitPlaybookRunForm.tsx, src/components/Playbooks/Settings/PlaybookSpecsForm.tsx, src/ui/Modal/index.tsx
- Add size for the modal from playbook params size
- Add the jsonSchemaURL property
- And closes #1751
=> Improve-playbook-params

src/components/SchemaResourcePage/index.tsx
=> fix: fix the settings health checks table not scrolling

src/components/BreadcrumbNav/ConfigsDetailsBreadCrumb.tsx, src/pages/config/ConfigChangesPage.tsx, src/pages/config/ConfigInsightsList.tsx, src/pages/config/ConfigList.tsx
=> Fix-config-type-navigation-not-working

src/components/Configs/Changes/ConfigChangeSeverity.tsx, src/components/Configs/Changes/ConfigChangesFilters/ChangeTypesDropdown.tsx, src/components/Configs/Changes/ConfigChangesFilters/ConfigChangesDateRangeFIlter.tsx, src/components/Configs/Changes/ConfigChangesFilters/ConfigChangesFilters.tsx, src/components/Configs/ConfigsListFilters/ConfigTypesDropdown.tsx, src/components/Configs/Insights/ConfigInsightsList.tsx, src/components/Configs/Insights/Filters/ConfigInsightsFilters.tsx, src/components/DataTable/index.tsx, src/components/JobsHistory/Filters/JobHistoryNames.tsx, src/components/JobsHistory/Filters/JobsHistoryFilters.tsx, src/components/JobsHistory/JobsHistorySettingsPage.tsx, src/components/JobsHistory/JobsHistoryTable.tsx, src/components/SchemaResourcePage/SchemaResourceEditJobsTab.tsx, src/pages/config/ConfigChangesPage.tsx, src/pages/config/ConfigInsightsList.tsx
=> fix: reset to first page, when applying filters for changes, insights and job history

src/components/CodeEditor/index.tsx, src/components/SpecEditor/HealthSpecEditor.tsx
=> 1734-When-editing-health-checks-specs-without-forms-can-be-confusing-to-know-what-they-fore

src/components/Authentication/Clerk/ClerkAuthSessionChecker.tsx
This reverts commit 118e5ad5627a571280f044874738a5a435bfdb74.
=> revert: let's use a normal redirect, without breaking app.flanksource.com

package-lock.json, package.json, src/App.tsx, src/components/Canary/CanaryInterface/minimal.tsx, src/components/Canary/CanaryStatsCard.tsx, src/components/Canary/HealthSummary/summary.tsx, src/components/Canary/index.tsx, src/components/Configs/Changes/ConfigDetailsChanges/ConfigDetailsChanges.tsx, src/components/Configs/Sidebar/ConfigsPanel.tsx, src/components/Hypothesis/HypothesisCommentsViewContainer/HypothesisCommentsViewContainer.tsx, src/components/IconButton/index.tsx, src/components/Layout/SearchLayout.tsx, src/components/Layout/SidebarLayout.tsx, src/components/Playbooks/Runs/Actions/PlaybookRunsActionItem.tsx, src/components/StatCard/index.tsx, src/components/TagList/TagList.tsx, src/components/Topology/Sidebar/ComponentChecks.tsx, src/components/Topology/Sidebar/TopologyConfigChanges/index.tsx, src/components/Topology/TopologyCard/Utils/FormatProperties.tsx, src/components/incidentTypeTag/index.tsx, src/pages/health.tsx, src/ui/Avatar/index.tsx
=> 1666-Canary-Page-on-Mission-Control---Health-Checks-Floating-Sidebar-Hidden-By-The-Mission-Control-Sidebar

src/api/query-hooks/index.ts, src/api/services/configs.ts, src/api/services/jobsHistory.ts, src/components/Configs/Changes/ConfigChangesFilters/ChangeTypesDropdown.tsx, src/components/Configs/Changes/ConfigChangesFilters/ConfigChangesFilters.tsx, src/components/JobsHistory/Filters/JobHistoryNames.tsx, src/components/JobsHistory/Filters/JobsHistoryFilters.tsx, src/components/TristateToggle/index.tsx, src/pages/config/ConfigChangesPage.tsx, src/ui/TristateReactSelect/TristateReactSelect.tsx
=> 1526-Config-changes-type-dropdown-multi-select

src/api/axios.ts, src/api/services/configs.ts, src/api/types/configs.ts, src/components/Configs/Changes/ConfigChangeHistory/index.tsx, src/components/Configs/Changes/ConfigChangeSeverity.tsx, src/components/Configs/Changes/ConfigChangesFilters/ConfigChangesDateRangeFIlter.tsx, src/components/Configs/Changes/ConfigsRelatedChanges/FilterBar/ConfigChangesToggledDeletedItems.tsx, src/components/Configs/Changes/ConfigsRelatedChanges/FilterBar/ConfigRelatedChangesFilters.tsx, src/components/Configs/ConfigDetailsTabs.tsx, src/components/Configs/ConfigRelationshipDropdown.tsx, src/components/Configs/ConfigRelationshipFilterBar.tsx, src/components/Configs/ConfigsListFilters/ConfigTypesDropdown.tsx, src/components/JobsHistory/Filters/JobsHistoryFilters.tsx, src/pages/config/details/ConfigDetailsChangesPage.tsx, src/pages/config/details/ConfigDetailsRelionshipsPage.tsx, src/ui/TimeRangePicker/RecentlyRanges.tsx, src/ui/TimeRangePicker/TimeRangeList.tsx, src/ui/TimeRangePicker/TimeRangePicker.tsx, src/ui/TimeRangePicker/TimeRangePickerBody.tsx, src/ui/TimeRangePicker/parseDateMath.ts, src/ui/TimeRangePicker/rangeOptions.ts, src/ui/TimeRangePicker/useTimeRangeParams.tsx, src/ui/TristateReactSelect/TristateReactSelect.tsx
=> feat: use related_configs for displaying related configs

src/components/FeatureFlags/FeatureFlagForm.tsx
=> fix: fix feature Flag (Add/Edit) Modal Cancel Button Not Working

src/components/Agents/AgentPage.tsx, src/components/Agents/List/AgentsTableColumns.tsx
=> feat: add agent online status & last pushed timestamp

src/api/query-hooks/playbooks.tsx, src/api/types/playbooks.ts, src/components/Playbooks/Runs/Actions/PlaybookRunActionFetch.tsx, src/components/Playbooks/Runs/Actions/PlaybookRunsActions.tsx, src/components/Playbooks/Runs/Actions/__tests__/PlaybookRunsAction.unit.test.tsx, src/components/Playbooks/Runs/Submit/SubmitPlaybookRunForm.tsx, src/components/Playbooks/Settings/PlaybookSpecCard.tsx, src/components/Playbooks/Settings/PlaybookSpecsForm.tsx, src/components/Playbooks/Settings/PlaybookSpecsList.tsx, src/components/Playbooks/Settings/__tests__/PlaybookSpecCard.unit.test.tsx, src/pages/playbooks/PlaybooksList.tsx
Closes #1811
Closes #1813
Closes #1809
=> 1811-Playbooks-category-grouping-improvement

src/components/BreadcrumbNav/ConfigsDetailsBreadCrumb.tsx, src/components/Configs/Changes/ConfigChangeHistory/index.tsx, src/components/Configs/ConfigDetailsTabs.tsx, src/components/Configs/Insights/Filters/ConfigInsightsSeverityDropdown.tsx, src/components/Dropdown/ComponentNamesDropdown/index.tsx, src/query-client.ts
=> 1789-catalog-breadcrumb-do-not-duplicate-config-item

src/api/axios.ts, src/api/services/search.ts, src/api/types/playbooks.ts, src/components/Forms/Formik/FormikResourceSelectorDropdown.tsx, src/components/Playbooks/Runs/Actions/__tests__/PlaybookRunsActionItem.unit.test.tsx, src/components/Playbooks/Runs/Filter/PlaybookRunsFilterBar.tsx, src/components/Playbooks/Runs/Submit/PlaybookSelectResource.tsx, src/components/Playbooks/Settings/__tests__/PlaybookSpecCard.unit.test.tsx, src/pages/playbooks/PlaybookRuns.tsx
Fixes #1795
Closes #1823
Closes #1457
=> 1795-Adjust-the-playbook-resource-selector-for-configs

src/api/types/playbooks.ts, src/components/Forms/Formik/FormikBytesTextField.tsx, src/components/Forms/Formik/FormikResourceSelectorDropdown.tsx, src/components/Forms/Formik/__tests__/FormikBytesTextField.unit.test.tsx, src/components/Forms/Formik/__tests__/FormikMillicoresTextField.unit.test.tsx, src/components/Playbooks/Runs/Submit/PlaybookParamsFieldsRenderer.tsx, src/components/Playbooks/Runs/Submit/PlaybookRunParams.tsx
=> 1831-Playbook-Param-Lookups---Switch-to-resource-selector-model

src/api/types/topology.ts, src/components/Topology/TopologyCard/index.tsx
=> fix: fix headline properties missing on mission-control

src/App.tsx, src/api/schemaResources.ts, src/components/Integrations/IntegrationsPage.tsx, src/components/Integrations/Table/IntegrationsTableColumns.tsx
=> feat: add integrations page and fix issues around pagination

src/components/Forms/Notifications/NotificationConfigurationForm.tsx, src/components/Forms/Notifications/NotificationsRecipientsTabs.tsx, src/components/Notifications/EditNotification.tsx, src/components/Notifications/NotificationsForm.tsx, src/components/Notifications/NotificationsTable.tsx, src/components/Notifications/notificationsTableColumns.tsx
Closes #1412
Closes #1818
Closes #1810
=> 1412-CRD-backed-notifications-shouldnt-be-editable-from-the-UI

src/components/Configs/Changes/ConfigChangeHistory/index.tsx, src/components/Configs/ConfigList/index.tsx, src/pages/config/ConfigChangesPage.tsx, src/pages/config/details/ConfigDetailsChangesPage.tsx
=> 1780-Change-sorting-should-be-done-serverdb-side

src/App.tsx, src/components/Configs/ConfigItem/index.tsx, src/components/Dropdown/ComponentLabelsDropdown/index.tsx, src/components/Dropdown/ComponentTypesDropdown/index.tsx, src/components/Hypothesis/Comments/index.tsx, src/components/IconButton/index.tsx, src/components/IncidentDetails/ResponderDetailsToolTip/index.tsx, src/components/Playbooks/Runs/services.tsx, src/components/Topology/TopologyPage/TopologyFilterBar.tsx, src/context/ConfigPageContext.tsx, src/context/FeatureFlagsContext.tsx, src/context/HealthPageContext.tsx, src/context/IncidentPageContext.tsx, src/context/UserAccessContext/UserAccessContext.tsx, src/pages/TopologyPage.tsx, src/ui/description/VerticalDescription.tsx
=> 1864-Topology-sorting-causes-an-extra-query-without-sorting-params

src/components/Configs/Graph/ConfigIntermediaryNodeReactFlowNode.tsx, src/ui/Graphs/Expand/useExpandCollapse.ts, src/ui/Graphs/RelationshipGraph.tsx
=> fix: improve intermediary node for configs layout

src/api/query-hooks/useFeatureFlags.tsx, src/api/services/properties.ts, src/components/FeatureFlags/FeatureFlagAddButton.tsx, src/components/FeatureFlags/FeatureFlagForm.tsx, src/components/FeatureFlags/FeatureFlagList.tsx, src/components/Forms/Formik/FormikSelect.tsx, src/components/Forms/Formik/FormikTextInput.tsx, src/context/FeatureFlagsContext.tsx, src/pages/Settings/FeatureFlagsPage.tsx, src/services/permissions/permissionsService.ts
=> refactor: use API properties endpoint instead of DB properties

src/api/query-hooks/index.ts, src/api/types/configs.ts, src/components/Configs/ConfigList/ConfigListColumn.tsx, src/components/Configs/Sidebar/ConfigDetails.tsx, src/components/Status/index.tsx
=> fix: use `health` instead of `status` in config details

src/components/Canary/HealthCheckEdit/index.tsx, src/components/Forms/SpecEditorForm.tsx, src/components/SchemaResourcePage/SchemaResourceEdit.tsx, src/components/SchemaResourcePage/SchemaResourceList.tsx, src/components/Settings/CRDSource.tsx, src/components/SpecEditor/ConfigScrapperSpecEditor.tsx
=> fix: CRD linked resources - Clicking on the resource should take you to the catalog CRD

src/api/services/configs.ts, src/components/Configs/Changes/ConfigChangesFilters/ConfigChangesFilters.tsx, src/components/Configs/Changes/ConfigChangesFilters/ConfigTypesTristateDropdown.tsx, src/components/Configs/Changes/ConfigsRelatedChanges/FilterBar/ConfigRelatedChangesFilters.tsx, src/pages/config/ConfigChangesPage.tsx, src/pages/config/details/ConfigDetailsChangesPage.tsx
=> feat: for config changes - use tri-state dropdown for config type

src/components/Forms/Health/HTTPHealthFormEditor.tsx, src/components/Forms/SpecEditorForm.tsx
=> Fix Issues on the Health Form

.eslintrc.js, package-lock.json, package.json, src/components/Canary/CanaryTabs.tsx, src/components/Configs/ConfigDetailsTabs.tsx, src/components/Configs/ConfigList/Cells/ConfigListTagsCell.tsx, src/components/Configs/ConfigList/ConfigListColumn.tsx, src/components/Configs/ConfigList/ConfigsTable.tsx, src/components/Configs/ConfigSummary/ConfigSummaryList.tsx, src/components/Configs/Sidebar/ConfigDetails.tsx, src/components/Configs/Sidebar/Utils/__tests__/formatConfigLabels.unit.test.tsx, src/components/Configs/Sidebar/Utils/formatConfigLabels.tsx, src/components/Configs/Sidebar/__tests__/ConfigDetails.unit.test.tsx, src/components/Status/index.tsx, src/components/Tag/Tag.tsx, src/components/Topology/Sidebar/TopologyDetails.tsx, src/components/Utils/__tests__/DisplayGroupedProperties.unit.test.tsx, src/pages/config/details/ConfigDetailsPage.tsx, src/ui/Chip/chip.tsx
=> fix: fix config tag display to only show value

src/api/types/configs.ts, src/components/Configs/Changes/ConfigChangeHistory/index.tsx, src/components/Layout/SearchLayout.tsx, src/components/Layout/minimal.js, src/components/Users/GetUserAvatar.tsx, src/components/Users/UserList/index.tsx, src/components/Users/UserProfile/UserProfile.tsx, src/pages/UsersPage.tsx
=> feat: add created by column for the config changes

pages/global.css, src/components/Configs/Changes/ConfigDetailsChanges/ConfigDetailsChanges.tsx, src/ui/DiffRenderer/DiffRenderer.tsx
=> fix: fix diff view styling being broken

src/api/schemaResources.ts, src/components/SchemaResourcePage/SchemaResourceList.tsx
=> fix: the last failed column in Catalog scraper is incorrect

src/api/query-hooks/index.ts, src/api/services/configs.ts, src/components/Configs/ConfigSummary/ConfigSummaryList.tsx, src/components/Configs/ConfigsListFilters/ConfigHealthyDropdown.tsx, src/components/Configs/ConfigsListFilters/ConfigLabelsDropdown.tsx, src/components/Configs/ConfigsListFilters/ConfigStatusDropdown.tsx, src/components/Configs/ConfigsListFilters/index.tsx, src/pages/config/ConfigList.tsx, src/ui/Dropdowns/MultiSelectDropdown.tsx
=> feat: add heatlh and status filters for configs

src/components/Forms/Health/AlertmanagerHealthFormEditor.tsx, src/components/Forms/Health/ElasticsearchHealthFormEditor.tsx, src/components/Forms/Health/ExecHealthFormEditor.tsx, src/components/Forms/Health/FolderHealthFormEditor.tsx, src/components/Forms/Health/HTTPHealthFormEditor.tsx, src/components/Forms/Health/ICMPHealthFormEditor.tsx, src/components/Forms/Health/MongoHealthFormEditor.tsx, src/components/Forms/Health/RedisHealthFormEditor.tsx, src/components/Forms/Health/TCPHealthFormEditor.tsx, src/components/Forms/SpecEditorForm.tsx, src/components/SchemaResourcePage/resourceTypes.tsx
=> fix: add top level name for canary, and sync with first check name

src/api/types/configs.ts, src/api/types/topology.ts, src/components/Configs/Sidebar/ConfigDetails.tsx, src/components/Topology/Sidebar/TopologyDetails.tsx, src/components/Topology/Sidebar/Utils/__tests__/formatTopologyProperties.unit.test.tsx, src/components/Topology/Sidebar/Utils/formatProperties.tsx, src/components/Topology/TopologyCard/Property.tsx, src/components/Topology/TopologyCard/Utils/FormatProperties.tsx, src/components/Topology/TopologyCard/index.tsx, src/components/Utils/DisplayDetailsRow.tsx, src/components/Utils/DisplayGroupedProperties.tsx
=> 1930-render-config-properties

src/api/query-hooks/index.ts, src/api/query-hooks/useAllConfigsQuery.ts, src/api/query-hooks/useConfigSummaryQuery.ts, src/api/services/configs.ts, src/components/Configs/ConfigList/ConfigsTable.tsx, src/components/Configs/ConfigListToggledDeletedItems/ConfigListToggledDeletedItems.tsx, src/components/Configs/ConfigSummary/ConfigSummaryList.tsx, src/components/Configs/ConfigSummary/utils/useGroupBySearchParam.tsx, src/components/Configs/ConfigsListFilters/ConfigGroupByDropdown.tsx, src/components/Configs/ConfigsListFilters/index.tsx, src/pages/config/ConfigList.tsx, src/pages/config/details/ConfigDetailsRelationshipsPage.tsx
Fixes #1952
Fixes #1941
Fixes #1953
=> 1952-hide-deleted-is-reversed-in-catalog-summary-relationships

src/api/services/jobsHistory.ts, src/components/Hooks/useCopyToClipboard.tsx, src/components/JobsHistory/JobsHistoryTable.tsx, src/components/JobsHistory/JobsHistoryTableColumn.tsx, src/components/JobsHistory/__tests__/JobsHistoryTable.unit.test.tsx
=> feat: link to resources from job history table

src/api/schemaResources.ts, src/components/Agents/AgentBadge.tsx, src/components/Integrations/Table/IntegrationsTableColumns.tsx, src/components/Integrations/Topology/TopologyResourceForm.tsx, src/components/SchemaResourcePage/SchemaResourceEdit.stories.tsx, src/components/SchemaResourcePage/SchemaResourceEdit.tsx, src/components/SchemaResourcePage/SchemaResourceList.tsx
=> fix: show agent details as a badge on the tables

src/api/query-hooks/useConfigRelationshipsQuery.tsx, src/components/Configs/ConfigsListFilters/ConfigGraphTableToggle.tsx, src/pages/config/details/ConfigDetailsRelationshipsPage.tsx
=> 1968-Config-relationships---Soft-toggle-not-working

src/components/Forms/Formik/FormikConfigEnvVarFields.tsx, src/components/Forms/Formik/utils/FormikEnvVarStaticView.tsx
=> fix: make EnvVar.value a password field

src/api/query-hooks/index.ts, src/api/services/topology.ts, src/components/Canary/CanaryPopup/CanaryCheckDetailsSpec.tsx, src/components/Canary/CanaryPopup/CheckDetails.tsx, src/components/Canary/CanaryPopup/CheckDetailsTabs.tsx, src/components/Canary/HealthCheckEdit/index.tsx
=> 1972-Health-check-spec-not-show-for-inlinemanual-canaries

src/components/Configs/ConfigsListFilters/index.tsx
=> fix: Catalog health filter does not work

package-lock.json, src/components/Forms/Formik/FormikCodeEditor.tsx, src/components/Forms/SpecEditorForm.tsx, src/components/Playbooks/Settings/PlaybookSpecsForm.tsx, src/components/SchemaResourcePage/SchemaResourceEdit.tsx, src/ui/Code/CodeBlock.stories.tsx, src/ui/Code/CodeEditor.stories.tsx, src/ui/Code/CodeEditor.tsx, src/ui/Code/JSONViewer.stories.tsx
=> 1988-Spec-unwrapping-should-only-be-applied-for-schema-resource-editors

src/components/Topology/TopologyCard/Utils/FormatProperties.tsx
=> fix: Property showing up as empty in UI

src/components/Agents/InstalAgentInstruction/CLIInstallAgent.tsx, src/components/Agents/InstalAgentInstruction/FluxInstallAgent.tsx, src/components/Agents/InstalAgentInstruction/useAgentsBaseURL.tsx
=> fix: incorrect host in agent generation output

src/components/Configs/Insights/Filters/ConfigInsightsFilters.tsx, src/pages/config/ConfigChangesPage.tsx, src/pages/config/ConfigInsightsList.tsx, src/pages/config/details/ConfigDetailsChangesPage.tsx
=> fix: Config changes - reset page to 1 when filters change

src/components/Configs/Changes/ConfigChangeHistory/index.tsx, src/components/Configs/Insights/ConfigInsightsList.tsx, src/components/JobsHistory/JobsHistorySettingsPage.tsx, src/components/JobsHistory/JobsHistoryTable.tsx, src/components/SchemaResourcePage/SchemaResourceEditJobsTab.tsx, src/pages/config/ConfigChangesPage.tsx, src/pages/config/details/ConfigDetailsChangesPage.tsx, src/ui/DataTable/Hooks/useReactTableSortState.tsx
Extracted from #1954 as it's blocked
=> refactor: create a hook to manage sorting state

src/api/query-hooks/index.ts, src/api/query-hooks/useConfigChangesHooks.ts, src/api/query-hooks/useGetConfigsChangesQuery.ts, src/api/services/configs.ts, src/components/Configs/Changes/ConfigChangesFilters/ConfigChangesFilters.tsx, src/components/Configs/Changes/ConfigChangesFilters/ConfigTagsDropdown.tsx, src/components/Configs/Changes/ConfigChangesFilters/ConfigTypesTristateDropdown.tsx, src/components/Configs/Changes/ConfigsRelatedChanges/FilterBar/ConfigChangesToggledDeletedItems.tsx, src/components/Configs/Changes/ConfigsRelatedChanges/FilterBar/ConfigRelatedChangesFilters.tsx, src/pages/config/ConfigChangesPage.tsx, src/pages/config/details/ConfigDetailsChangesPage.tsx, src/ui/Dropdowns/TristateReactSelect.tsx
=> 1961-Changes-tag-filter

src/api/types/configs.ts, src/components/Configs/Changes/ConfigChangeTable.stories.tsx, src/components/Configs/Changes/ConfigChangeTable.tsx, src/components/Configs/Changes/ConfigChangesFilters/ConfigChangeSeverity.tsx, src/components/Configs/Changes/ConfigChangesFilters/ConfigChangesFilters.tsx, src/components/Configs/ConfigList/Cells/ConfigListTagsCell.tsx, src/components/Forms/Formik/FormikSearchInputClearable.tsx, src/pages/config/ConfigChangesPage.tsx, src/pages/config/details/ConfigDetailsChangesPage.tsx, src/ui/Icons/ChangeIcon.tsx, src/ui/Icons/Icon.tsx
Closes #2018
Relies on https://github.com/flanksource/flanksource-icons/pull/1
=> 2018-catalog-changes-improvements

src/api/services/configs.ts
=> fix: switch to using in and notin for tag dropdown

src/components/Authentication/Kratos/KratosLogin.tsx
=> fix: fix the login page unable to redirect and crashing when logged in

src/components/Playbooks/Runs/Filter/PlaybookRunsFilterBar.tsx, src/pages/playbooks/PlaybookRunsPage.tsx
=> fix: default time filter to 7 days for playbooks runs

pages/profile-settings/[[...profile-settings]].tsx, src/components/Authentication/Kratos/KratosProfileSettings.tsx
Accidentally worked on this issue before reliased it wasn't assigned to me, but it was a relatively minor fix, so pushing the PR.
Fixes #2003
=> fix: fix blank screen after updating the profile settings

src/api/query-hooks/useConfigRelationshipsQuery.tsx, src/api/services/configs.ts, src/api/types/configs.ts, src/components/Configs/ConfigRelationshipFilterBar.tsx, src/components/Configs/ConfigsListFilters/ConfigGraphDirectionToggle.tsx, src/components/Configs/ConfigsListFilters/ConfigGraphTableToggle.tsx, src/components/Configs/Graph/ConfigIntermediaryNodeReactFlowNode.tsx, src/components/Configs/Graph/ConfigItemReactFlowNode.tsx, src/components/Configs/Graph/ConfigRelationshipGraph.tsx, src/components/Configs/Graph/__tests__/__snapshots__/formatConfigsForGraph.unit.test.ts.snap, src/components/Configs/Graph/__tests__/formatConfigsForGraph.unit.test.ts, src/components/Configs/Graph/__tests__/mocks/argo-argocd-applicationset-controller.ts, src/components/Configs/Graph/__tests__/mocks/argo-argocd-notifications-controller.ts, src/components/Configs/Graph/formatConfigsForGraph.ts, src/pages/config/details/ConfigDetailsRelationshipsPage.tsx, src/ui/BreadcrumbNav/ConfigsDetailsBreadCrumb.tsx, src/ui/Graphs/Expand/types.ts, src/ui/Graphs/Expand/useExpandCollapse.ts, src/ui/Graphs/RelationshipGraph.tsx
=> 1967-Incorrect-intermediaryphantom-nodes

src/components/JobsHistory/JobsHistoryTable.tsx, src/components/JobsHistory/JobsHistoryTableColumn.tsx
=> feat: add agent column for job history table

src/components/Topology/TopologyBreadcrumbs/index.tsx
Some of the minor refactoring I made when I worked on the PR, can be merged as the [backed fix](https://github.com/flanksource/duty/issues/861) is being worked on,
Part of #2043
=> Improvements to the bread crumbs for topology

src/api/query-hooks/useConfigRelationshipsQuery.tsx, src/components/Configs/Changes/ConfigsRelatedChanges/FilterBar/ConfigRelationshipToggles.tsx, src/components/Configs/Graph/ConfigIntermediaryNodeReactFlowNode.tsx, src/components/Configs/Graph/ConfigItemReactFlowNode.tsx, src/components/Configs/Graph/ConfigRelationshipGraph.tsx, src/components/Configs/Graph/__tests__/__snapshots__/formatConfigsForGraph.unit.test.ts.snap, src/components/Configs/Graph/__tests__/formatConfigsForGraph.unit.test.ts, src/components/Configs/Graph/formatConfigsForGraph.ts, src/ui/FormControls/Toggle.tsx, src/ui/Graphs/Controls/GraphEdgeTypeToggle.tsx, src/ui/Graphs/Expand/useAnimatedNodes.ts, src/ui/Graphs/Expand/useExpandCollapse.ts, src/ui/Graphs/RelationshipGraph.tsx
=> Graph-improvements-on-nodes

src/api/query-hooks/useConfigSummaryQuery.ts, src/components/Configs/ConfigSummary/Cells/ConfigSummaryTableVirtualAggregateColumn.tsx, src/components/Configs/ConfigSummary/Cells/ConfigSummaryVirtualColumnCell.tsx, src/components/Configs/ConfigSummary/ConfigSummaryList.tsx, src/components/Configs/ConfigSummary/utils/useGroupBySearchParam.tsx, src/components/Configs/ConfigsListFilters/ConfigGroupByDropdown.tsx, src/components/Configs/ConfigsTypeIcon.tsx, src/components/Topology/TopologyBreadcrumbs/index.tsx, src/pages/config/ConfigList.tsx
=> feat: add group by type class for config summary

src/api/services/search.ts, src/components/Forms/Formik/FormikResourceSelectorDropdown.tsx, src/components/Forms/Formik/FormikSelectDropdown.tsx, src/components/Playbooks/Settings/PlaybookSpecsList.tsx, src/ui/Tags/Tag.tsx
=> 2064-Config-Selector-Dropdown---Add-tags

src/App.tsx, src/api/query-hooks/useConfigChecksQuery.tsx, src/api/services/configs.ts, src/api/types/configs.ts, src/components/Canary/CanaryPopup/ChecksDetailsModal.tsx, src/components/Canary/CanaryTable.tsx, src/components/Canary/ChecksListing.tsx, src/components/Canary/HealthChecks/CheckLink.tsx, src/components/Canary/aggregate.tsx, src/components/Configs/ConfigChecks/ConfigChecksTable.tsx, src/components/Configs/ConfigDetailsTabs.tsx, src/components/Configs/ConfigTabsLinks.tsx, src/pages/config/details/ConfigDetailsChecksPage.tsx
=> feat: add health checks tab to the configs tab

src/api/schemaResources.ts, src/components/Forms/FormikFilterForm.tsx, src/components/Integrations/Table/IntegrationsTableColumns.tsx, src/components/JobsHistory/JobsHistoryDetails.tsx, src/components/JobsHistory/JobsHistoryTable.tsx, src/components/SchemaResourcePage/SchemaResourceList.tsx, src/ui/DataTable/Hooks/useReactTableSortState.tsx, src/ui/Tabs/Tabs.tsx
=> 2062-display-config-scrape-summary

src/components/Agents/Add/AddAgentForm.tsx, src/components/Agents/InstalAgentInstruction/InstallAgentModal.tsx, src/components/Connections/ConnectionFormModal.tsx, src/components/Integrations/Add/AddIntegrationModal.tsx, src/components/Playbooks/Settings/PlaybookSpecsForm.tsx, src/components/SchemaResourcePage/AddSchemaResourceModal.tsx, src/components/SpecEditor/SpecEditor.tsx, src/ui/Buttons/HelpLink.tsx, src/ui/Modal/index.tsx
=> 1955-Link-all-docs

chart/templates/hpa.yaml
Fixes: https://github.com/flanksource/flanksource-ui/issues/2084
=> chore: update autoscaler version in chart

src/api/types/configs.ts, src/components/Configs/Sidebar/ConfigDetails.tsx
=> feat: add indicator of stale configs on the sidebar

package-lock.json, package.json, src/App.tsx, src/components/Authentication/Kratos/KratosLogin.tsx, src/components/Authentication/Kratos/ory/errors.tsx, src/ui/ToasterWithCloseButton.stories.tsx, src/ui/ToasterWithCloseButton.tsx
=> 1944-Toast-error-messages-should-have-a-close-icon

src/components/Topology/Sidebar/TopologyActionBar.tsx
Closes #2043
Example: http://localhost:3000/topology/018fdd98-f8de-40fb-23c3-452f9687aad9?sortBy=status&sortOrder=desc
=> chore: remove ability to hide components

src/components/Configs/Changes/ConfigChangeTable.tsx, src/components/Configs/ConfigList/Cells/ConfigListTagsCell.tsx, src/ui/DataTable/FilterByCellValue.tsx, src/ui/Tags/Tag.tsx
=> 2111-Tag---IncludeExclude

src/components/Agents/Add/AddAgent.tsx, src/components/Agents/AgentPage.tsx
=> fix: don't cache query for agents and refetch on update

src/components/Configs/Sidebar/ConfigDetails.tsx
=> fix: only show last scraped warning if the item is not deleted.

src/components/Forms/Formik/FormikCodeEditor.tsx, src/components/Playbooks/Runs/Submit/PlaybookRunParams.tsx
=> 2092-Changing-playbook-param-doesnt-update-default-form-values

src/api/query-hooks/useConfigSummaryQuery.ts, src/components/Configs/ConfigSummary/ConfigSummaryList.tsx, src/components/Configs/ConfigSummary/ConfigSummaryTypeFavorite.tsx
=> feat: add mechanism to favorite Config Types in config summary

src/components/Forms/Formik/FormikCheckbox.tsx, src/components/Playbooks/Runs/Submit/PlaybookParamsFieldsRenderer.tsx
=> fix: fix playbooks params checkbox being sent as boolean causing error

src/pages/config/details/ConfigDetailsChangesPage.tsx
=> fix: remove unnecessary extra call to get id,name,config_class,type

src/components/Configs/Changes/ConfigChangesFilters/ConfigChangesFilters.tsx, src/components/Configs/Changes/ConfigsRelatedChanges/FilterBar/ConfigRelatedChangesFilters.tsx, src/components/Configs/ConfigList/Cells/ConfigListTagsCell.tsx, src/components/Configs/ConfigRelationshipFilterBar.tsx, src/components/Configs/ConfigsListFilters/ConfigGraphTableToggle.tsx, src/components/Configs/ConfigsListFilters/ConfigsListFilters.tsx, src/components/Configs/Graph/ConfigItemReactFlowNode.tsx, src/ui/Badge/Badge.tsx, src/ui/FormControls/TextInputClearable.tsx, src/ui/FormControls/Toggle.tsx, src/ui/Tags/Tag.tsx
=> fix: add tooltip to show full tag name for tags

src/components/Playbooks/Runs/PlaybookRunsList.tsx, src/components/Topology/TopologyLink.tsx, src/pages/playbooks/PlaybookRunsPage.tsx
=> 1949-resources-are-not-displayed-in-playbook-run-history

src/components/Playbooks/Settings/PlaybookSpecsForm.tsx
=> 2143-Editing-an-already-existing-playbook-spec-always-takes-the-cursor-to-last-line

src/api/query-hooks/playbooks.tsx, src/components/Playbooks/PlaybookSpecModalTitle.tsx, src/components/Playbooks/Runs/Actions/PlaybookRunsActions.tsx, src/components/Playbooks/Runs/Submit/PlaybookRunParams.tsx, src/components/Playbooks/Runs/Submit/ReRunPlaybookWithParamsButton.tsx, src/components/Playbooks/Runs/Submit/SubmitPlaybookRunForm.tsx, src/components/Playbooks/Runs/Submit/__tests__/SelectPlaybookToRun.unit.test.tsx, src/components/Playbooks/Runs/Submit/__tests__/SubmitPlaybookRunForm.unit.test.tsx, src/components/Playbooks/Settings/PlaybookSpecIcon.tsx, src/ui/ToasterWithCloseButton.stories.tsx, src/ui/ToasterWithCloseButton.tsx, src/ui/description/VerticalDescription.tsx
=> 1738-Playbook-Option-to-re-run-a-playbook-run-with-the-same-parameters

package-lock.json, package.json, src/components/Playbooks/Runs/Actions/PlaybookResultsDropdownButton.tsx, src/components/Playbooks/Runs/Actions/PlaybookRunActionFetch.tsx, src/components/Playbooks/Runs/Actions/PlaybookRunsActions.tsx, src/components/Playbooks/Runs/Actions/PlaybooksActionsResults.stories.tsx, src/components/Playbooks/Runs/Actions/PlaybooksActionsResults.tsx
=> feat: add button to download playbooks actions results to file

src/components/Settings/ResourceTable.tsx
=> fix: fix icon size consistency issues for scrappers

src/components/Notifications/notificationsTableColumns.tsx
Fixes: #2167 
Also removed the incident events to not confuse users
=> chore: update notification events

src/api/services/playbooks.ts, src/components/Playbooks/Runs/Actions/PlaybookRunsActionItem.tsx, src/components/Playbooks/Runs/Actions/PlaybookRunsActions.tsx, src/pages/playbooks/PlaybookRunsDetails.tsx, src/pages/playbooks/PlaybookRunsPage.tsx, src/pages/playbooks/PlaybooksList.tsx, src/ui/Icons/PlaybookStatusIcon.tsx, src/ui/description/VerticalDescription.tsx
=> fix: make improvements to the playbook run results

src/api/types/playbooks.ts, src/components/Forms/Formik/FormikResourceSelectorDropdown.tsx
=> fix: improve the search mechanism for the playbook resource selector

src/components/Canary/HealthChecks/CheckLink.tsx, src/components/Playbooks/Runs/PlaybookRunsList.tsx, src/components/Playbooks/Runs/Submit/ReRunPlaybookWithParamsButton.tsx, src/components/Topology/TopologyLink.tsx, src/pages/playbooks/PlaybookRunsDetails.tsx, src/pages/playbooks/PlaybookRunsPage.tsx
=> 2170-Playbook-improvements

package-lock.json, package.json, src/components/Authentication/Kratos/KratosUserProfileDropdown.tsx, src/components/KubeConfig/AddKubeConfigModal.tsx, src/components/Users/UserProfile.tsx, src/ui/StepperList.stories.tsx, src/ui/StepperList.tsx
=> 2149-Add-kubeconfig-dialog

package-lock.json, package.json, src/api/resolve.ts, src/api/schemaResources.ts, src/api/services/agents.ts, src/api/services/comments.ts, src/api/services/configs.ts, src/api/services/evidence.ts, src/api/services/hypothesis.ts, src/api/services/incident.ts, src/api/services/jobsHistory.ts, src/api/services/notifications.ts, src/api/services/playbooks.ts, src/api/services/properties.ts, src/api/services/responder.ts, src/api/services/teams.ts, src/api/services/topology.ts, src/api/services/users.ts, src/components/JobsHistory/JobsHistorySettingsPage.tsx, src/components/JobsHistory/JobsHistoryTable.tsx, src/components/SchemaResourcePage/SchemaResourceEditJobsTab.tsx, src/ui/DataTable/Hooks/useReactTablePaginationState.tsx, src/ui/MRTDataTable/MRTDataTable.tsx
=> 2187-Paging-is-broken

src/components/Notifications/notificationsTableColumns.tsx, src/ui/MRTDataTable/MRTDataTable.tsx
=> 2206-Notifications---Rename-success-column-to-sent-+-extract-the-value-correctly

src/components/Forms/Formik/FormikCodeEditor.tsx, src/components/Playbooks/Runs/Submit/PlaybookRunParams.tsx, src/components/Playbooks/Runs/Submit/ReRunPlaybookWithParamsButton.tsx, src/components/Playbooks/Runs/Submit/SubmitPlaybookRunForm.tsx, src/components/Playbooks/Settings/PlaybookSpecsForm.tsx
=> fix: fix playbook spec being saved as string

package-lock.json, src/App.tsx, src/components/Configs/ConfigPageTabs.tsx, src/components/Configs/Sidebar/ConfigDetails.tsx, src/components/Configs/Sidebar/__tests__/ConfigDetails.unit.test.tsx, src/components/Forms/SpecEditorForm.tsx, src/components/Integrations/Topology/TopologyResourceForm.tsx, src/components/JobsHistory/JobsHistoryTableColumn.tsx, src/components/SchemaResourcePage/SchemaResourceEditJobsTab.tsx, src/components/Settings/CanEditResource.tsx, src/components/SpecEditor/SpecEditor.tsx, src/pages/config/settings/ConfigScrapersEditPage.tsx, src/pages/config/settings/ConfigScrapersPage.tsx
=> feat: move settings -> Scrappers to Catalog -> Settings

src/api/types/playbooks.ts, src/pages/playbooks/PlaybookRunsDetails.tsx, src/ui/Icons/PlaybookStatusIcon.tsx
=> feat: refresh playbook runs every 5 seconds while running/waiting

src/api/types/configs.ts, src/components/Configs/Changes/ConfigChangeTable.tsx
=> feat: add count and firstObserved columns to changes table

src/api/query-hooks/index.ts, src/api/services/configs.ts, src/components/Configs/Changes/ConfigChangeTable.tsx, src/components/Configs/Changes/ConfigChangesFilters/ConfigTagsDropdown.tsx, src/components/Configs/ConfigList/Cells/ConfigListTagsCell.tsx, src/ui/DataTable/FilterByCellValue.tsx, src/ui/Dropdowns/TristateReactSelect.tsx, src/ui/Tags/Tag.tsx
=> 2169-Tags---Should-be-able-to-include-a-cluster-tag-but-then-exclude-1-or-more-namespace-tags

package-lock.json, package.json, src/components/Forms/Formik/FormikCodeEditor.tsx, src/ui/Code/CodeEditor.tsx
=> fix: improve the code editor performance when writing

src/ui/Icons/Icon.stories.tsx, src/ui/Icons/Icon.tsx
=> feat: add support for color to the Icons component

src/api/query-hooks/playbooks.tsx, src/api/services/playbooks.ts, src/api/types/playbooks.ts, src/components/Playbooks/PlaybookSpecModalTitle.tsx, src/components/Playbooks/Runs/Actions/ShowParamaters/ViewPlaybookParamsModal.tsx, src/components/Playbooks/Runs/Filter/PlaybookSpecsDropdown.tsx, src/components/Playbooks/Runs/Submit/PlaybookRunParams.tsx, src/components/Playbooks/Runs/Submit/ReRunPlaybookWithParamsButton.tsx, src/components/Playbooks/Runs/Submit/SubmitPlaybookRunForm.tsx, src/components/Playbooks/Runs/Submit/__tests__/SubmitPlaybookRunForm.unit.test.tsx, src/components/Playbooks/Settings/PlaybookSpecCard.tsx, src/components/Playbooks/Settings/PlaybookSpecIcon.tsx, src/components/Playbooks/Settings/PlaybookSpecsForm.tsx, src/pages/playbooks/PlaybookRunsPage.tsx
Depends on https://github.com/flanksource/duty/pull/967
Fixes #2195
=> fix: switch to the title column for playbooks instead of name

package-lock.json, package.json, src/ui/Dropdowns/TristateReactSelect.tsx
Extracted from https://github.com/flanksource/flanksource-ui/pull/2188
Switches to react-windowed-select which is a variation of react-select with virtualization build in
=> fix: fix performance issues around tri-state react-select

src/pages/config/ConfigList.tsx
=> fix: fix grouping is ignored when filtering by label for catalog

package-lock.json, src/components/Integrations/Table/IntegrationsTableColumns.tsx, src/components/Integrations/Topology/EditTopologyResource.tsx, src/components/Settings/CRDSource.tsx, src/components/Settings/ResourceSettingsSourceLink.tsx
=> fix: don't show crd link, when source is Push

src/api/query-hooks/useNotificationsQuery.ts, src/components/Notifications/NotificationsForm.tsx, src/components/Notifications/notificationsTableColumns.tsx
=> feat: add repeat_interval to notifications

src/api/axios.ts, src/api/query-hooks/health.tsx, src/api/resolve.ts, src/components/Canary/CanaryPopup/CheckRunNow.tsx, src/query-client.ts, src/ui/Icons/Icon.tsx
=> 2229-Run-now---error-messages

.storybook/preview.tsx, src/components/Topology/TopologyCard/FormatProperty.tsx, src/ui/Age/Age.stories.tsx, src/ui/Age/Age.tsx
=> chore: show an age with a full tooltip of timestamp

src/components/Layout/SearchLayout.tsx, src/components/Permissions/AuthorizationAccessCheck.tsx, src/components/Permissions/UnAuhorizedPage.tsx
=> fix: always show the navbar up top when displaying unauthorized page

package-lock.json, package.json, src/components/Configs/ConfigsTypeIcon.tsx, src/ui/Icons/Icon.tsx
=> fix: fix missing icons for mission control configs

src/components/Forms/Formik/FormikResourceSelectorDropdown.tsx
Improves performance for large lists of items
Fixes #2220
=> fix: use react-widowed-select for resource selector

src/components/Permissions/AuthorizationAccessCheck.tsx, src/context/UserAccessContext/UserAccessContext.tsx, src/hooks/ReactQuery/roles.tsx
=> fix: fix unauthorized if flashed before protected page is shown

src/components/Authentication/Kratos/KratosLogin.tsx
=> fix: show error message when login fails due to invalid credentials

src/pages/config/details/ConfigDetailsInsightsPage.tsx, src/pages/config/details/ConfigDetailsPage.tsx
=> fix: fix page incorrect page title on config page

pages/index.tsx, src/api/axios.ts
=> fix: fix login screen is show for canary checker image

src/components/Configs/ConfigLink/ConfigLink.tsx, src/components/Configs/Sidebar/__tests__/ConfigsPanel.unit.test.tsx, src/components/Connections/ConnectionFormModal.tsx, src/components/Connections/ConnectionSpecEditor.tsx, src/components/Connections/connectionTypes.tsx
=> 2230-Edit-Connection---Only-show-connection-types-on-add-ottherwise-show-spec

src/api/query-hooks/index.ts, src/components/Configs/ConfigsListFilters/ConfigLabelsDropdown.tsx
=> fix: fix issue with catalog page crashing after inactivity

src/components/Forms/Formik/FormikNotificationsTemplateField.tsx
=> fix: allow template to be set to default, and custom for code editor

src/components/Configs/Sidebar/ConfigDetails.tsx, src/ui/Age/Age.tsx, src/ui/BreadcrumbNav/ConfigsDetailsBreadCrumb.tsx
=> feat: highlight deleted configs and improve how they deleted configs are shown

src/components/JobsHistory/JobsHistoryDetails.tsx, src/components/JobsHistory/JobsHistoryTable.tsx, src/components/JobsHistory/JobsHistoryTableColumn.tsx, src/components/Notifications/notificationsTableColumns.tsx
=> fix: fix job history details modal error issues

src/api/services/notifications.ts, src/components/Notifications/NotificationDetailsModal.tsx, src/components/Notifications/NotificationResourceDisplay.tsx, src/components/Notifications/NotificationSendHistory.tsx, src/components/Notifications/NotificationSendHistory/NotificationDetails.tsx
=> feat: make improvements to notification details modal

src/components/Configs/ConfigItem/ConfigItem.stories.tsx, src/ui/DataTable/FilterByCellValue.tsx, src/ui/Dropdowns/TristateReactSelect.tsx, src/ui/FormControls/TristateToggle.tsx
=> 2309-In-job-historys-job-search-box-if-I-am-typing-something-and-hit-enter-the-first-selection-should-be-selected

src/api/types/configs.ts, src/components/Configs/ConfigList/Cells/ConfigListChangeCell.tsx, src/components/Configs/Graph/ConfigItemReactFlowNode.tsx
=> fix: update UI to reflect to configs view changes

src/components/Configs/Changes/ConfigChangeTable.tsx
=> fix: tags rendering as analysis

src/api/services/notifications.ts, src/api/types/notifications.ts, src/components/Notifications/NotificationTabsLinks.tsx, src/components/Notifications/SilenceNotificationForm/EditNotificationSilenceModal.tsx, src/components/Notifications/SilenceNotificationForm/NotificationSilenceForm.tsx, src/components/Notifications/SilenceNotificationsList.tsx, src/pages/Settings/notifications/NotificationSilencedAddPage.tsx, src/ui/Dates/TimeRangePicker/TimeRangePicker.tsx
=> 2322-Notification-Silence

src/api/services/notifications.ts, src/components/Notifications/NotificationSendHistory/NotificationDetails.tsx, src/components/Notifications/Rules/NotificationsRulesTable.tsx, src/components/Notifications/SilenceNotificationForm/EditNotificationSilenceModal.tsx, src/components/Notifications/SilenceNotificationsList.tsx, src/components/Topology/TopologyLink.tsx, src/ui/MRTDataTable/MRTDataTable.tsx
=> Notifications-improvements

src/api/query-hooks/useUserAPI.tsx, src/api/services/users.ts, src/pages/UsersPage.tsx
=> 2307-When-inviting-a-user-the-assigned-role-is-not-persisted

src/components/Forms/Formik/FormikResourceSelectorDropdown.tsx
=> fix: update message for when the user hasn't started typing and options are empty

src/api/types/notifications.ts, src/components/Notifications/Rules/notificationsRulesTableColumns.tsx
=> fix: show error on notifications_summary when it's there

src/api/types/health.ts, src/components/Canary/CanaryPopup/StatusHistory/StatusHistory.tsx, src/components/Status/index.tsx
=> 2335-Canary-modal-history-improvements

src/pages/Settings/notifications/NotificationSilencedAddPage.tsx
=> fix: revalidate and refetch silences on creation

src/api/services/playbooks.ts
=> 2305-Pending-playbooks-waiting-for-approval-are-not-shown-in-the-Runs-page

src/components/Configs/Changes/ConfigChangesFilters/ConfigChangesFilters.tsx, src/components/Configs/ConfigPageTabs.tsx, src/components/Configs/ConfigsTypeIcon.tsx, src/pages/config/ConfigChangesPage.tsx
=> fix: fix inconsistent font for catalog breadcrumb

src/components/JobsHistory/__tests__/JobsHistoryTable.unit.test.tsx, src/utils/__tests__/common.unit.test.ts, src/utils/common.ts
=> fix: fix incorrect job name

src/api/query-hooks/index.ts, src/ui/Dropdowns/TristateReactSelect.tsx
=> fix:  fix filter by health and status not working

src/components/Connections/ConnectionForm.tsx, src/pages/Settings/ConnectionsPage.tsx
=> fix: fix sorting doesn't work on /settings/connections table

src/components/Topology/Sidebar/TopologyDetails.tsx
=> fix: show component status and reason in sidebar

src/components/Forms/Formik/FormikDurationPicker.tsx, src/components/Notifications/SilenceNotificationForm/NotificationSilenceForm.tsx, src/components/Notifications/SilenceNotificationsList.tsx
=> fix: fix edit Silence durations fails with date math

src/api/services/configs.ts, src/components/Configs/Changes/ConfigChangesFilters/ChangeTypesDropdown.tsx
=> 2314-Dropdown-size-is-very-small

src/components/Configs/Changes/ConfigChangesFilters/ConfigChangesFilters.tsx, src/components/Configs/Changes/ConfigsRelatedChanges/FilterBar/ConfigRelatedChangesFilters.tsx, src/pages/config/details/ConfigDetailsChangesPage.tsx, src/pages/playbooks/PlaybookRunsPage.tsx, src/pages/playbooks/PlaybooksList.tsx, src/ui/DataTable/Hooks/useReactTablePaginationState.tsx
=> fix: remember page sizes for tables on local storage

src/api/services/playbooks.ts, src/api/types/playbooks.ts, src/components/Playbooks/Runs/Actions/PlaybookRunsActions.tsx, src/components/Playbooks/Runs/Actions/PlaybookRunsApprovalActionItem.tsx, src/components/Playbooks/Runs/Actions/PlaybookRunsApprovalActionsResults.tsx, src/ui/Avatar/index.tsx
=> feat: show approval step in actions list

src/components/Playbooks/Runs/Submit/PlaybookParamsFieldsRenderer.tsx
resolves: https://github.com/flanksource/flanksource-ui/issues/2425
=> feat(playbook): better parameter default handling

src/api/services/playbooks.ts, src/api/types/playbooks.ts, src/components/Playbooks/Runs/Actions/PlaybookRunsActionItem.tsx, src/components/Playbooks/Runs/Actions/PlaybookRunsActions.tsx
* Fix avatar in playbook run creator
merge after: https://github.com/flanksource/duty/pull/1257
=> fix: show agent on actions

src/api/services/permissions.ts
resolves: https://github.com/flanksource/flanksource-ui/issues/2441
=> fix: hide deleted permissions

src/components/Forms/Formik/FormikResourceSelectorDropdown.tsx, src/components/Playbooks/Runs/Submit/PlaybookSelectResource.tsx, src/ui/Buttons/HelpLink.tsx
resolves: https://github.com/flanksource/flanksource-ui/issues/2448
=> feat: Help link on playbooks resource selector

src/context/UserAccessContext/UserAccessContext.tsx, src/context/UserAccessContext/permissions.ts
resolves: https://github.com/flanksource/flanksource-ui/issues/2475
=> fix(guest role): viewing permission

src/api/services/permissions.ts, src/api/types/permissions.ts, src/components/Permissions/PermissionsTable.tsx, src/components/Permissions/PermissionsView.tsx
* Display tags & agents based permissions
* 
resolves: https://github.com/flanksource/flanksource-ui/issues/2440
=> feat: new subjects in permissions

src/components/Configs/ConfigList/ConfigsTable.tsx, src/components/Configs/ConfigList/MRTConfigListColumn.tsx
resolves: https://github.com/flanksource/flanksource-ui/issues/2439
=> feat: clickable configs

Dockerfile
* Remove health check. The container doesn't have curl.
=> fix(Dockerfile): Let buildx handle arch specific builds.

src/api/services/playbooks.ts, src/components/Playbooks/Runs/Actions/PlaybookRunsActions.tsx, src/components/Playbooks/Runs/CancelPlaybookButton.tsx, src/components/Playbooks/Runs/CancelPlaybookRunModal.tsx
related: https://github.com/flanksource/mission-control/issues/1911
=> feat: Playbook cancellation

src/components/Notifications/NotificationSendHistory.tsx, src/components/Notifications/NotificationSendHistory/NotificationDetails.tsx, src/components/Playbooks/Runs/Actions/PlaybooksActionsResults.tsx, src/components/Utils/Markdown.tsx, src/utils/slack.tsx
resolves: https://github.com/flanksource/mission-control/issues/1951
=> feat: render slack blocks in markdown

src/api/axios.ts, src/api/services/artifacts.ts, src/api/services/playbooks.ts, src/api/types/playbooks.ts, src/components/Playbooks/Runs/Actions/PlaybookRunsActions.tsx, src/components/Playbooks/Runs/Actions/PlaybooksActionsResults.tsx, src/ui/Tabs/Tabs.tsx, src/utils/slack.tsx
related: https://github.com/flanksource/mission-control/issues/1961
https://github.com/user-attachments/assets/e7453ef7-d78d-4622-a5ac-ec005c20cb73
=> feat: display artifacts on playbook actions

src/components/Playbooks/Runs/Actions/PlaybooksActionsResults.tsx
resolves: https://github.com/flanksource/flanksource-ui/issues/2507
=> fix: playbook results rendering

src/api/services/playbooks.ts, src/api/types/playbooks.ts, src/components/Playbooks/Runs/Actions/PlaybookResultsDropdownButton.tsx, src/components/Playbooks/Runs/Actions/PlaybookRunActionFetch.tsx, src/components/Playbooks/Runs/Actions/PlaybookRunsActions.tsx, src/components/Playbooks/Runs/Actions/PlaybooksActionsResults.stories.tsx, src/components/Playbooks/Runs/Actions/PlaybooksActionsResults.tsx, src/components/Playbooks/Runs/Actions/__tests__/PlaybookRunsAction.unit.test.tsx, src/pages/playbooks/PlaybookRunsDetails.tsx
resolves: https://github.com/flanksource/flanksource-ui/issues/2516
resolves: https://github.com/flanksource/flanksource-ui/issues/2519
=> feat: Download playbook action tab content

src/api/types/playbooks.ts, src/components/Playbooks/Runs/CancelPlaybookButton.tsx, src/components/Playbooks/Runs/Filter/PlaybookStatusDropdown.tsx, src/components/Playbooks/Runs/PlaybookRunsStatus.tsx, src/ui/Icons/PlaybookStatusIcon.tsx
resolves: https://github.com/flanksource/flanksource-ui/issues/2526
=> Playbook: Run timed out & Action waiting for children

.gitignore, src/components/Notifications/NotificationSendHistory.tsx, src/components/Notifications/NotificationsStatusCell.tsx, src/components/Playbooks/Runs/Actions/PlaybookRunsActions.tsx, src/ui/MRTDataTable/MRTDataTable.tsx
resolves: https://github.com/flanksource/flanksource-ui/issues/2504
resolves: https://github.com/flanksource/flanksource-ui/issues/2493
=> feat: notification grouping with native MRT

src/api/types/configs.ts, src/api/types/topology.ts, src/components/Canary/HealthChecks/CheckLink.tsx, src/components/Configs/ConfigLink/ConfigLink.tsx, src/components/Notifications/NotificationResourceDisplay.tsx, src/components/Notifications/NotificationSendHistory.tsx
resolves: https://github.com/flanksource/flanksource-ui/issues/2522
<details>
<summary>Old</summary>
</details>
**New**
=> feat: show health & status of resources in notification send history

src/api/services/notifications.ts, src/components/Forms/Formik/FormikSearchInputClearable.tsx, src/components/Notifications/Filters/NotificationFilterBar.tsx, src/components/Notifications/NotificationSendHistory.tsx, src/pages/Settings/notifications/NotificationsPage.tsx
resolves: https://github.com/flanksource/flanksource-ui/issues/2465
* hide `skipped` and `silenced` notifications by default
=> feat: notification resource search

src/components/Playbooks/Runs/Actions/PlaybooksActionsResults.tsx
merge code & headers into a single "response" tab
=> fix: HTTP action display

src/api/types/notifications.ts, src/components/Notifications/NotificationSendHistory/NotificationDetails.tsx
resolves: https://github.com/flanksource/flanksource-ui/issues/2528
=> feat: Display silencer

src/components/Notifications/SilenceNotificationForm/NotificationSilenceDirectForm.tsx, src/components/Notifications/SilenceNotificationForm/NotificationSilenceForm.tsx
resolves: https://github.com/flanksource/flanksource-ui/issues/2538
=> feat: updating silence form with indefinite time range

src/components/Playbooks/Runs/Actions/PlaybookRunsActions.tsx, src/components/Playbooks/Runs/Actions/PlaybooksActionsResults.tsx
related: https://github.com/flanksource/mission-control/issues/1829
=> feat: display the total cost of a playbook run

src/components/Playbooks/Runs/Actions/PlaybookRunsActions.tsx
resolves: https://github.com/flanksource/flanksource-ui/issues/2558
=> fix: display input/output tokens for free models

src/api/types/topology.ts, src/components/Topology/TopologyCard/FormatProperty.tsx
related: https://github.com/flanksource/config-db/issues/1577
=> feat: Badge Property type

src/components/Configs/ConfigsTypeIcon.tsx
resolves: https://github.com/flanksource/flanksource-ui/issues/2574
=> feat: configtype tooltip

src/components/Notifications/NotificationSendHistorySummary.tsx, src/components/Notifications/NotificationTabsLinks.tsx
resolves: https://github.com/flanksource/flanksource-ui/issues/2582
=> fix(notification navigation): Preserve filters

src/components/Forms/Formik/FormikCodeEditor.tsx, src/components/Notifications/SilenceNotificationForm/NotificationSilenceForm.tsx
resolves: https://github.com/flanksource/flanksource-ui/issues/2569
=> feat: silence inline examples

src/pages/views/components/SingleView.tsx
resolves: https://github.com/flanksource/flanksource-ui/issues/2624
=> fix: view error handling

src/components/Tokens/Add/CreateTokenForm.tsx, src/components/Users/UserProfile.tsx
Fixes: https://github.com/flanksource/flanksource-ui/issues/2631
=> chore: mcp scope should be ticked when modal is opened from `Setup MCP`

src/api/services/notifications.ts, src/api/types/health.ts, src/api/types/notifications.ts, src/api/types/topology.ts, src/components/Notifications/SilenceNotificationForm/FormikNotificationResourceField.tsx, src/components/Notifications/SilenceNotificationForm/NotificationSilenceForm.tsx
Fixes: https://github.com/flanksource/flanksource-ui/issues/2633
=> feat: revamp notification silences ui
