flanksource/flanksource-ui

src/components/Canary/filter.js

Further fixes for Tarun's null checks crash issues for canary-checker

fix: null checks for filterChecks, filterChecksByText functions

---

.gitignore
.storybook/main.js
.storybook/preview.js
postcss.config.js
src/components/Canary/CanaryPopup/CheckDetails.js
src/components/Canary/Columns/index.js
src/components/CanaryInterface/minimal.js
tailwind.config.js

Fixed issue where tailwind styles aren't loaded in the built version of storybook (`npm run build-storybook`).
Had to add `postcss.config.js` and make some slight changes in `tailwind.config.js` where:
`purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"]`
is changed into
`content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"]` 
Also added a gitignore entry for `./storybook-static`, and re-fix some recurring linting errors from `main` branch.

Fix: Tailwind styles absent in build-storybook 

---

package.json

This is the supported list with the new config (run `npm run checkbrowserslist` to see):
```and_chr 92
and_ff 90
and_qq 10.4
and_uc 12.12
android 92
android 4.4.3-4.4.4
baidu 7.12
chrome 92
chrome 91
chrome 90
chrome 89
chrome 87
chrome 85
edge 92
edge 91
firefox 90
firefox 89
firefox 78
ios_saf 14.5-14.7
ios_saf 14.0-14.4
ios_saf 13.4-13.7
kaios 2.5
op_mob 64
opera 77
opera 76
safari 14.1
safari 14
safari 13.1
samsung 14.0
samsung 13.0```

chore: update browserlist

---

src/components/TopologyCard/index.tsx

bug: Leaf topology cards should not include themselves as a subcomponent

---

.github/workflows/lint.yaml
.github/workflows/publish.yaml
.github/workflows/test.yaml
.releaserc

This will release pre-releases from the master branch and production releases every time there is a commit to a branch called `release`

ci: configure a release branch for production releases

---

package-lock.json

When you run npm i, the package-lock file has some changes to it, which should never happen unless installing/updating dependencies.

chore: ensure package.json lockfile is up to date

---

src/components/ReactSelectDropdown/index.tsx
src/components/TopologyPopover/topologySort.tsx

@moshloop was also updated `TopologyPopover` background for page design consistency. 😊

694: Dropdowns should always have a white background

---

src/components/DataTable/Pagination/Pagination.tsx
src/pages/config/configChanges.tsx

Shows a minimum of 50 items, all the way to 200.
Closes #741

fix: increase the count of config items shown per page

---

next.config.js

All localhost and netlify re-writes all now proxied as received to the backend with this PR.

fix: fix failing nextjs re-writes for local and netlify

---

src/components/SchemaResourcePage/SchemaResourceEdit.tsx

This is done to keep user in editing flow once he clicks on edit instead of allowing him to navigate to other sections.

fix: while editing resource spec hide remaining tabs

---

src/components/ConfigSidebar/ConfigDetails.tsx

Closes #824
https://user-images.githubusercontent.com/34602861/221948659-d54be93d-0b04-4fa9-8684-67710bcbe024.mov

fix: hide details not found text when loading on config sidebar

---

src/api/services/configs.ts
src/components/ConfigChangeHistory/index.tsx
src/components/ConfigList/Cells/ConfigListAnalysisCell.tsx
src/components/ConfigList/Cells/ConfigListChangeCell.tsx
src/components/ConfigList/Cells/ConfigListTagsCell.tsx
src/components/ConfigList/ConfigListColumn.tsx
src/components/ConfigList/index.tsx
src/components/DataTable/index.tsx
src/components/JobsHistory/JobsHistoryTable.tsx
src/components/Logs/Table/LogsTable.tsx
src/components/Logs/Table/LogsTableCells.tsx
src/components/Popover/Popover.tsx
src/components/TagList/TagList.tsx
src/components/UserList/index.tsx
src/hooks/useMouseActivity.ts
src/hooks/userPreferences.ts

fix: retain scroll & expansion state of config list table

---

src/components/Changelog/IncidentChangelog.tsx
src/components/CollapsiblePanel/index.tsx
src/components/IncidentDetails/DefinitionOfDone/IncidentsDefinitionOfDone.tsx
src/components/IncidentDetails/DefinitionOfDone/IncidentsDefinitionOfDoneItem.tsx
src/components/IncidentDetails/IncidentDetailsPanel.tsx
src/components/IncidentDetails/IncidentSidebar.tsx
src/components/IncidentDetails/Responders.tsx
src/components/SlidingSideBar/index.tsx

fix: incident details sidebar ui/ux improvements

---

package-lock.json

updates caniuse version to remove unnecessary pollyfills as new browsers
gain adoption
https://github.com/browserslist/update-db#why-you-need-to-call-it-regularly

chore:  run npx update-browserslist-db@latest

---

src/api/query-hooks/index.ts
src/api/query-hooks/mutations/evidence.tsx
src/components/Badge/CountBadge.tsx
src/components/Changelog/IncidentChangelog.tsx
src/components/CollapsiblePanel/index.tsx
src/components/ConfigChanges/index.tsx
src/components/ConfigComponents/index.tsx
src/components/ConfigInsights/index.tsx
src/components/ConfigSidebar/ConfigDetails.tsx
src/components/CostDetails/CostDetails.tsx
src/components/Hypothesis/EvidenceSection/index.tsx
src/components/Hypothesis/HypothesisCommentsViewContainer/HypothesisCommentsViewContainer.tsx
src/components/Icon/index.tsx
src/components/IncidentDetails/AddDefinitionOfDone/AddAutoDefinitionOfDone.tsx
src/components/IncidentDetails/AddDefinitionOfDone/AddDefinitionOfDoneHome.tsx
src/components/IncidentDetails/AddDefinitionOfDone/AddManualDefinitionOfDone.tsx
src/components/IncidentDetails/AddDefinitionOfDone/useAddCommentAsDoD.tsx
src/components/IncidentDetails/DefinitionOfDone/EditEvidenceDefinitionOfDoneComment.tsx
src/components/IncidentDetails/DefinitionOfDone/EditEvidenceDefinitionOfDoneScript.tsx
src/components/IncidentDetails/DefinitionOfDone/EvidenceView/index.tsx
src/components/IncidentDetails/DefinitionOfDone/IncidentsDefinitionOfDone.tsx
src/components/IncidentDetails/DefinitionOfDone/IncidentsDefinitionOfDoneItem.tsx
src/components/Sidebars/incidents.tsx
src/components/SlidingSideBar/SlidingSideBar.stories.tsx
src/components/Tabs/Tabs.tsx
src/components/TopologyConfigChanges/index.tsx
src/components/TopologySidebar/ComponentTeams.tsx
src/components/TopologySidebar/TopologyActionBar.tsx
src/components/TopologySidebar/TopologySidebar.tsx

- add count badge component do display counts and to adjust style based on the value.
- topology sidebar menu items are re arranged.
- definition done item views ui/ux fixes.
- sorted definition of done items before displaying.
- auto collapse collapsible panel when there is no data based on the dataCount property.
- fixed the issue of comment box on comments view of incidents details is hidden when there are no hypothesis.
- fixed the styling issues of tab in active state.
- sliding sidebar storybook changes.
- fixed the issue of manually added definition of done item not being shown until refresh is clicked.

fix: ui improvements

---

src/components/ory/ui/NodeInputDefault.tsx

closes #985
I have found this form validation in the dashboard.
**Previous style for signin & signup page validation**
**current style**
[Loom Video](https://www.loom.com/share/42f57e90f1794d5eb18577a6c67eceff)

refactor: improve signin and signup page validation errors styling

---

src/api/schemaResources.ts
src/components/SchemaResourcePage/SchemaResourceList.tsx
src/components/SchemaResourcePage/resourceTypes.tsx

Closes #1086
- login with your credentials
- go to health check create page by clicking on the health sub menu item fo setting menu item on the sidebar
- you will be shown list of health checks and schedule column value of that table is read from spec
- click on the plus icon on the navbar and observe there is no separate schedule option in the health check form.

fix: remove schedule field from health check resource form

---

src/api/query-hooks/index.ts
src/api/query-hooks/useGetConfigChangesByConfigChangeIdQuery.ts
src/api/services/configs.ts
src/components/ConfigChangeHistory/index.tsx
src/components/ConfigChanges/Cells/ConfigChangeAgeCell.tsx
src/components/ConfigChanges/Cells/ConfigChangeNameCell.tsx
src/components/ConfigChanges/index.tsx
src/components/ConfigDetailsChanges/ConfigDetailsChanges.tsx
src/components/DataTable/Pagination/Pagination.tsx
src/components/DataTable/index.tsx
src/components/InfiniteTable/InfiniteTable.tsx
src/components/Sidebars/configs.tsx
src/components/Tabs/TabbedLinks.tsx
src/pages/config/ConfigDetailsChangesPage.tsx

Closes #937 
- added a new component `InfiniteTable` which provides virtual paging support.
- modified existing `DataTable` component to add support for virtual paging.
- code refactored to integrate above changes
- open the [url](https://deploy-preview-1029--goofy-euclid-75956c.netlify.app/configs/0185578e-22c6-1165-1ef1-97f707f264ff)
- login with your credentials
- go to the config changes section in the sidebar
- try scrolling and observe data getting loaded as we scroll to the end.
- when all the data is loaded observe the total count in the config changes header and the sum of all the records returned in the api calls should match.

937 config changes panel add virtual paging

---

src/api/query-hooks/useComponentConfigRelationshipQuery.ts
src/api/services/configs.ts
src/components/ConfigLink/ConfigLink.tsx
src/components/Dropdown/DropdownWithActions.tsx
src/components/Sidebars/configs.tsx
src/components/TopologyConfigLinkModal/TopologyConfigLinkModal.tsx
src/components/TopologySidebar/TopologyActionBar.tsx
src/utils/common.ts

Closes #853
* adds support for manually linking a config to a component.
* adds support for deleting manually linked config.
* open [url](https://deploy-preview-1070--goofy-euclid-75956c.netlify.app/topology/01862990-0ae8-0cd9-e57e-9056061f9459?sortBy=status&sortOrder=desc)
* go to the action bar section on the sidebar
* click on `Link to config` action button this will open up a modal
* link any config and observe the recently linked config being shown under `Configs` section on the sidebar.

feat: add manual component config linking support

---

src/App.tsx
src/api/query-hooks/useJobsHistoryQuery.ts
src/api/services/jobsHistory.ts
src/components/DataTable/index.tsx
src/components/JobsHistory/Filters/JobHistoryNames.tsx
src/components/JobsHistory/Filters/JobsHistoryFilters.tsx
src/components/JobsHistory/JobsHistoryDetails.tsx
src/components/JobsHistory/JobsHistorySettingsPage.tsx
src/components/JobsHistory/JobsHistoryTable.tsx
src/components/JobsHistory/JobsHistoryTableColumn.tsx
src/components/SchemaResourcePage/SchemaResourceEditJobsTab.tsx
src/utils/common.ts
src/utils/date.ts

786- Job History Improvements

---

src/pages/incident/IncidentListPage.tsx

fix: refetch on mount incidents to get latest copy

---

.env
pages/api/[...paths].ts
pages/auth-state-checker.tsx

Removing the fallback (default) URL, which was created using org slug, and solely relying on the backend_url in the public metadata, will return a 500 error when backend_url hasn't been set.

Fix-auth-mishaps

---

src/components/ConfigAnalysis/ConfigInsightsList.tsx
src/components/ConfigAnalysisLink/ConfigInsightsDetailsModal.tsx
src/components/ConfigChangeHistory/index.tsx
src/components/ConfigDetailsChanges/ConfigDetailsChanges.tsx
src/components/ConfigLink/ConfigLink.tsx
src/components/Modal/ModalTitleListItems.tsx
src/components/Sidebars/configs.tsx

Overflow on last item now shows ellipses
Closes #1379

fix: re-order change and analysis modal titles and add overflow

---

src/components/Forms/Formik/FormikSelectDropdown.tsx
src/components/SchemaResourcePage/ConfigScrapperIcon.tsx
src/components/SchemaResourcePage/SchemaResourceList.tsx
src/components/Select/Select.js

1393-add-icon-config-scrapers

---

src/api/axios.ts
src/api/query-hooks/playbooks.tsx
src/api/services/playbooks.ts
src/components/Canary/minimal.tsx
src/components/ConfigSidebar/ConfigActionBar.tsx
src/components/ConfigSidebar/index.tsx
src/components/InfiniteTable/InfiniteTable.tsx
src/components/Insights/Insights.tsx
src/components/Insights/cells/ConfigInsightAgeCell.tsx
src/components/Menu/index.tsx
src/components/Playbooks/Runs/AddPlaybookToRunParams.tsx
src/components/Playbooks/Runs/PlaybookRunsSidePanel.tsx
src/components/Playbooks/Runs/SelectPlaybookToRun.tsx
src/components/Playbooks/Runs/SubmitPlaybookRunForm.tsx
src/components/Playbooks/Settings/PlaybookSpecsForm.tsx
src/components/Playbooks/Settings/PlaybookSpecsTable.tsx
src/components/TopologyCard/TopologyDropdownMenu.tsx
src/components/TopologySidebar/TopologyActionBar.tsx
src/components/TopologySidebar/TopologySidebar.tsx

Build on top of the #1357 PR
Closes #1353

1353-components-playbooks

---

next.config.js
src/App.tsx
src/api/axios.ts
src/api/query-hooks/mutations/useUpsertAgentMutations.tsx
src/api/query-hooks/useAgentsQuery.tsx
src/api/query-hooks/useNotificationsQuery.ts
src/api/services/agents.ts
src/components/Agents/Add/AddAgent.tsx
src/components/Agents/Add/AddAgentForm.tsx
src/components/Agents/Add/__tests__/AddAgentForm.unit.test.tsx
src/components/Agents/AgentPage.tsx
src/components/Agents/DeleteAgentButton.tsx
src/components/Agents/InstallAgentModal.tsx
src/components/Agents/List/AgentsTable.tsx
src/components/Agents/List/AgentsTableColumns.tsx
src/components/Agents/__tests__/DeleteAgentButton.unit.test.tsx
src/components/Agents/__tests__/InstallAgentModal.unit.test.tsx
src/components/Authentication/Clerk/ClerkAuthContextProvider.tsx
src/components/Authentication/Kratos/KratosAuthContextProvider.tsx
src/components/CodeBlock/CodeBlock.tsx
src/components/CodeBlock/__tests__/CodeBlock.unit.test.tsx
src/components/Dialogs/ConfirmationPromptDialog.tsx
src/components/Forms/Formik/FormikKeyValueMapField.tsx
src/components/Forms/Formik/__tests__/FormikKeyValueMapField.unit.test.tsx
src/components/Hooks/useCopyToClipboard.tsx
src/context/UserAccessContext/permissions.ts
src/context/index.ts
src/services/permissions/features.ts

feat: add agents page with list of agents

---

src/api/query-hooks/playbooks.tsx
src/api/services/playbooks.ts
src/components/Canary/minimal.tsx
src/components/ConfigSidebar/ConfigActionBar.tsx
src/components/Playbooks/Runs/Submit/AddPlaybookToRunParams.tsx
src/components/Playbooks/Runs/Submit/SelectPlaybookToRun.tsx
src/components/Playbooks/Runs/Submit/SubmitPlaybookRunForm.tsx
src/components/Playbooks/Runs/Submit/__tests__/SelectPlaybookToRun.unit.test.tsx
src/components/Playbooks/Runs/Submit/__tests__/SubmitPlaybookRunForm.unit.test.tsx
src/components/TopologySidebar/TopologyActionBar.tsx
src/pages/playbooks/PlaybookRuns.tsx
src/pages/playbooks/PlaybookRunsDetails.tsx
src/pages/playbooks/PlaybooksList.tsx

1445 playbook improvements

---

src/components/Connections/ConnectionForm.tsx
src/components/Connections/connectionTypes.tsx

1451-connection-properties-need-stored-mapstring-string

---

src/components/TopologyFilters/TopologyFilterBar.tsx
src/components/TopologyPopover/index.tsx
src/components/TopologyPopover/topologySort.tsx

1409-health-dropdown-click-target-text-not-button

---

.github/workflows/lint.yaml
.github/workflows/test.yaml
src/components/Playbooks/Runs/Submit/PlaybooksDropdownMenu.tsx

- Transition component was breaking netlfiy build errors
- Switched node to v20 (current Long Term Support, and enabled caching of NPM dependencies) in Github Action as this was also failing in this PR, while increasing memory for production build to 4gb.

fix: fix build failing due to TS error from transition component

---

src/components/JobsHistory/JobHistoryStatusColumn.tsx
src/components/JobsHistory/JobsHistoryDetails.tsx
src/components/Notifications/notificationsTableColumns.tsx

1387-notification-table-cannot-see-error

---

src/components/Canary/CanaryTableColumns.tsx
src/components/Canary/Columns/index.tsx
src/components/Canary/Rows/lib.ts
src/components/Canary/grouping.ts
src/components/Canary/table.tsx

1453-treat-check-names-grouping

---

src/components/UserList/index.tsx
src/pages/UsersPage.tsx

1498-users-table-action-menu-rendered-inside-cell

---

pages/organizations/switcher/[[...organization-switcher]].tsx

This is the page you land in after signup

fix: hide personal workspace on default org switcher

---

src/components/Connections/ConnectionForm.tsx
src/components/Connections/ConnectionFormModal.tsx
src/components/Connections/ConnectionListView.tsx
src/components/Connections/ConnectionsList.tsx
src/components/Connections/FormikConnectionOptionsSwitchField.tsx
src/components/Connections/RenderConnectionFormFields.tsx
src/components/Connections/__tests__/ConnectionForm.unit.test.tsx
src/components/Connections/__tests__/ConnectionFormModal.unit.test.tsx
src/components/Connections/connectionTypes.tsx
src/components/Forms/Formik/FormikCompactEnvVarSource.tsx
src/components/Forms/Formik/FormikConnectionField.tsx
src/components/Forms/Formik/utils/FormikEnvVarK8SView.tsx
src/components/Forms/Formik/utils/FormikEnvVarStaticView.tsx
src/pages/Settings/ConnectionsPage.tsx

feat: add new git connection type for connections

---

package-lock.json
package.json
pages/api/[...paths].ts
pages/login/[[...index]].tsx
src/components/Authentication/Kratos/KratosLogin.tsx
src/components/Authentication/Kratos/KratosLogoutButton.tsx
src/components/SkeletonLoader/FormSkeletonLoader.tsx
src/components/ory/helpers.ts
src/components/ory/hooks.ts
src/components/ory/ui/Flow.tsx
src/components/ory/ui/NodeInputButton.tsx
src/components/ory/ui/NodeInputSubmit.tsx

Improve Kratos Login Flow

---

src/components/Sidebars/configs.tsx
src/components/Topology/Sidebar/TopologyActionBar.tsx
src/components/Topology/Sidebar/Utils/TopologyConfigsActionsDropdown.tsx
src/components/Topology/Sidebar/Utils/__tests__/TopologyConfigsActionDropdown.unit.test.tsx
src/components/TopologyCard/TopologyDropdownMenu.tsx
src/components/TopologyConfigLinkModal/TopologyConfigLinkModal.tsx

Me and Yash for a moment visually thought the current delete button was a badge, by making it red, we are making it visually distinguishable and actionable
Closes #1529

fix: make the delete button distinguishable from badge and add tooltip

---

package-lock.json
package.json
pages/_app.tsx
src/App.tsx
src/components/Authentication/Clerk/ClerkAuthContextProvider.tsx
src/components/Authentication/Clerk/InstanceCreationInProgress.tsx
src/components/Intercom/BootIntercom.tsx
src/components/Intercom/SetupIntercom.tsx
src/components/Layout/SearchLayout.tsx
src/ui/MenuBar/HelpDropdown.tsx

fix: hide intercom chat launcher by default

---

src/api/query-hooks/useComponentConfigRelationshipQuery.ts
src/api/services/configs.ts
src/components/Sidebars/configs.tsx

1447-hide-catalog-link-delete-button-non-manual-links

---

.github/workflows/publish.yaml

CI builds are being skipped due to a filter and we use an untagged latest version of semantic release here directly.
Using the github action from other repos

fix: update semantic release workflow

---

src/components/Utils/DisplayDetailsRow.tsx

fix: config details not scrolling and instead squashing text when height is not enough for content

---

src/components/Topology/TopologyCard/index.tsx

fix: don't show empty headline properties

---

src/components/Configs/ConfigSummary/Cells/ConfigSummaryHealthCells.tsx
src/components/Configs/ConfigSummary/ConfigSummaryList.tsx
src/components/Configs/ConfigsListFilters/ConfigHealthyDropdown.tsx
src/components/Configs/ConfigsListFilters/index.tsx
src/components/Forms/Formik/FormikSearchInputClearable.tsx
src/components/Forms/FormikFilterForm.tsx

fix: fix incorrect name for health filter in catalog name

---

src/api/types/configs.ts
src/components/Configs/ConfigList/ConfigsRelationshipsTable.tsx
src/components/Configs/Graph/ConfigRelationshipGraph.tsx
src/components/Configs/Graph/__tests__/__snapshots__/formatConfigsForGraph.unit.test.ts.snap
src/components/Configs/Graph/__tests__/formatConfigsForGraph.unit.test.ts
src/components/Configs/Graph/__tests__/mocks/argo-argocd-applicationset-controller.ts
src/components/Configs/Graph/__tests__/mocks/argo-argocd-notifications-controller.ts
src/components/Configs/Graph/formatConfigsForGraph.ts
src/pages/config/details/ConfigDetailsRelationshipsPage.tsx
src/ui/Graphs/RelationshipGraph.tsx

Due to position changing, as expand and collapse works, fitView is still the best, so we retain zoom levels
Fixes #1999

Make Improvements to the Config Relationships - Graph and Table

---

src/api/query-hooks/useAgentsQuery.tsx
src/api/query-hooks/useConfigChangesHooks.ts
src/api/services/configs.ts
src/components/Agents/AgentPage.tsx
src/components/Agents/List/AgentsTable.tsx
src/components/Configs/Changes/ConfigChangesFilters/ConfigChangesFilters.tsx
src/components/Configs/Changes/ConfigsRelatedChanges/FilterBar/ConfigRelatedChangesFilters.tsx
src/hooks/useConfigChangesArbitraryFilters.tsx
src/pages/config/ConfigChangesPage.tsx
src/ui/DataTable/FilterByCellValue.tsx
src/ui/Dropdowns/TristateReactSelect.tsx

fix: fix config changes filter by cell issues around encoding and colons

---

src/components/Canary/CanaryFilters/DropdownWrapper.tsx
src/components/Canary/CanaryFilters/HidePassingToggle.tsx
src/components/Canary/CanaryFilters/TopBar/CanaryFiltersBar.tsx
src/components/Canary/CanaryFilters/TopBar/ChecksGroupByDropdown.tsx
src/components/Canary/CanaryFilters/TopBar/ChecksTabByDropdown.tsx
src/components/Canary/CanaryInterface.tsx
src/components/Canary/CanaryTable.tsx
src/components/Canary/ChecksListing.tsx
src/components/Canary/index.tsx
src/components/Canary/useHealthUserSettings.tsx

2031-In-health-page---on-first-load-we-hide-passing-ones-by-default-However-the-Hide-Passing-toggle-is-switched-off

---

src/components/Status/index.tsx

fix: "warning" should be orange for config status

---

src/api/services/configs.ts

chore: remove recursive when downstream and upstream aren't selected

---

src/components/Agents/Add/AddAgentForm.tsx
src/components/Agents/InstalAgentInstruction/CLIInstallAgent.tsx
src/components/Agents/InstalAgentInstruction/FluxInstallAgent.tsx
src/components/Authentication/Clerk/ClerkAuthContextProvider.tsx
src/context/index.ts

feat: add pushTelemetry.topologyName option/prefill in spec generator of agent

---

chart/templates/ingress.yaml
chart/values.schema.json
chart/values.yaml

Fixes: https://github.com/flanksource/flanksource-ui/issues/2252

chore: use ingress.ingressClassName in helm chart over ingress.className

---

src/components/Connections/ConnectionForm.tsx
src/components/Connections/ConnectionFormModal.tsx
src/components/Forms/SpecEditorForm.tsx
src/components/Integrations/Topology/TopologyResourceForm.tsx
src/components/Notifications/NotificationsForm.tsx
src/components/Settings/CRDSource.tsx
src/components/Settings/CanEditResource.tsx

fix: Don't allow edit/delete for CRD created notifications

---

src/api/types/topology.ts
src/components/Topology/TopologyCard/index.tsx

The color of the component card should depend on the `.health` attribute and not status anymore
Let me know if this needs to be changed anywhere else as well

fix: use topology.health instead of status

---

chart/values.schema.json
chart/values.yaml

Public demo releases were failing due to this
```
Observed Generation:   9
Reason:                UpgradeFailed
Status:                False
Type:                  Ready
Last Transition Time:  2024-09-24T17:47:57Z
Message:               Helm upgrade failed for release default/default-mission-control-demo-mission-control-tenant with chart mission-control@0.1.192: values don't meet the specifications of the schema(s) in the following chart(s):
flanksource-ui:
- global.labels: Additional property flanksource.com/clerk-org-id is not allowed
Observed Generation:  9
```
@moshloop Also, when I ran the schema.json in Makefile, it gave the following 
```diff
diff --git a/chart/values.schema.json b/chart/values.schema.json
index 3a618f37..3e3be600 100644
--- a/chart/values.schema.json
+++ …
```

fix: helm schema json to allow global.labels

---

src/api/query-hooks/index.ts
src/api/query-hooks/useConfigSummaryQuery.ts
src/api/services/notifications.ts
src/components/Configs/ConfigList/Cells/ConfigListTagsCell.tsx
src/components/Configs/ConfigList/Cells/MRTConfigListTagsCell.tsx
src/components/Configs/ConfigList/MRTConfigListColumn.tsx
src/components/Configs/ConfigSummary/ConfigSummaryList.tsx
src/components/Configs/ConfigsListFilters/ConfigLabelsDropdown.tsx

2165-Catalog---Add-includeexclude-shortcuts-in-Catalog-tag-list

---

src/components/Notifications/SilenceNotificationsList.tsx

fix: mark expired silences with a strikethrough

---

src/components/Canary/CanaryCards.tsx
src/components/Canary/Columns/index.tsx
src/components/Canary/renderers.tsx

2189-Add-spacing-around-and-graysacale-in-check-names

---

.gitignore
src/api/query-hooks/useNotificationsQuery.ts
src/api/services/permissions.ts
src/api/types/notifications.ts
src/api/types/permissions.ts
src/api/types/playbooks.ts
src/components/Forms/Formik/FormikNotificationDropdown.tsx
src/components/Notifications/NotificationSendHistory.tsx
src/components/Notifications/NotificationsStatusCell.tsx
src/components/Permissions/ManagePermissions/Forms/PermissionForm.tsx
src/components/Permissions/ManagePermissions/Forms/PermissionSubjectControls.tsx
src/components/Permissions/PermissionsTable.tsx
src/components/Permissions/PermissionsView.tsx
src/components/Playbooks/Runs/Actions/PlaybookRunsActions.tsx

resolves: https://github.com/flanksource/flanksource-ui/issues/2420

feat: playbook as notification recipient

---

package-lock.json
package.json
src/components/Connections/ConnectionFormModal.tsx
src/components/Connections/connectionTypes.tsx
src/ui/Icons/Icon.tsx

* fix icon for google cloud storage & GCP
resolves: https://github.com/flanksource/flanksource-ui/issues/2427

feat: new connections for LLMS

---

src/api/query-hooks/useCheck.ts
src/api/query-hooks/useComponent.ts
src/api/query-hooks/useConfigRelationshipsQuery.tsx
src/api/services/check.ts
src/api/services/configs.ts
src/api/services/notifications.ts
src/api/services/topology.ts
src/api/types/configs.ts
src/api/types/notifications.ts
src/components/Notifications/NotificationTabsLinks.tsx
src/components/Notifications/SilenceNotificationForm/FormikNotificationDirectResourceField.tsx
src/components/Notifications/SilenceNotificationForm/FormikNotificationField.tsx
src/components/Notifications/SilenceNotificationForm/FormikNotificationResourceField.tsx
src/components/Notifications/SilenceNotificationForm/NotificationSilenceDirectForm.tsx
src/components/Notifications/SilenceNotificationForm/NotificationSilenceForm.tsx
src/components/Notifications/SilenceNotificationsList.tsx
src/pages/Settings/notifications/NotificationSilencedAddPage.tsx
src/pages/Settings/notifications/NotificationsSilencedPage.tsx
src/pages/config/details/ConfigDetailsRelationshipsPage.tsx
src/ui/Age/Age.tsx
src/ui/Dates/TimeRangePicker/TimeRangePicker.tsx
src/ui/Dates/TimeRangePicker/rangeOptions.ts

resolves: https://github.com/flanksource/flanksource-ui/issues/2423
resolves: https://github.com/flanksource/flanksource-ui/issues/2449
resolves: https://github.com/flanksource/flanksource-ui/issues/2453

feat: Notification silence new fields

---

Dockerfile

v20 had this issue https://github.com/nodejs/docker-node/issues/1946
4 different attempts to build the docker image kept timing out https://github.com/flanksource/flanksource-ui/actions/runs/13920533256

feat(Dockerfile): use node v22.14 LTS

---

.gitignore
src/components/Configs/ConfigList/ConfigsTable.tsx

resolves: https://github.com/flanksource/flanksource-ui/issues/2532
The right click still needs to happen right on the config name though.

fix: make the config row clickable

---

src/components/Notifications/NotificationSendHistory/NotificationDetails.tsx

slack notifications are in the format: `[{"blocks": {...}}]`
while, slack notifications from playbook actions are in the format: `{"blocks": {...}}`

feat: support slack body rendering from notification actions

---

src/components/Agents/InstalAgentInstruction/useAgentsBaseURL.tsx
src/components/Authentication/Kratos/KratosUserProfileDropdown.tsx
src/components/Tokens/Add/TokenDisplayModal.tsx
src/components/Tokens/TokenDetailsModal.tsx
src/components/Users/UserProfile.tsx
src/ui/Code/CodeBlock.tsx
src/ui/HelmSnippet/CLISnippet.tsx
src/ui/HelmSnippet/__tests__/CLISnippet.unit.test.tsx
src/ui/HelmSnippet/__tests__/__snapshots__/CLISnippet.unit.test.tsx.snap

@moshloop Also added syntax highlighting for Codeblock
Once this is merged, I'll add this in MCP docs and use it as source for MCP Client setup to make this file the source of truth

feat: add MCP Setup wizard

---

src/pages/audit-report/components/View/View.tsx
src/pages/audit-report/components/View/panels/DurationPanel.tsx
src/pages/audit-report/components/View/panels/index.ts
src/pages/audit-report/types/index.ts

resolves: https://github.com/flanksource/flanksource-ui/issues/2626

feat(View): Duration Panel
